#!/usr/bin/env node
// verify-built.js: the ninth gate. Every inline <script> in every built page
// must actually parse.
//
// This exists because a single invalid escape sequence in one quiz option
// (\) where \" was meant) made an 8,876-line script fail at parse time. The
// page served a 200, weighed the right number of kilobytes, passed all eight
// gates, and rendered a header with nothing under it. Content gates check what
// the source says. Nothing checked whether the thing we ship can run.
//
// Two things were wrong with the first version of this gate, and both meant it
// never saw the bytes that actually ship:
//
//   1. TARGETS is a list of PRE-ASSEMBLY paths. The pages GitHub Pages serves
//      live under _site/ and are not all copies: the home page has been through
//      substitution, and every built blog page is generated by build-blog.js and
//      appears nowhere in this list. All of them carry inline script. So the
//      page most likely to break was the one page never parsed. This now walks
//      _site/**/*.html whenever _site exists, in addition to the targets.
//   2. A missing target was console.log-skipped. A gate that silently passes
//      when its input is absent is not a gate; a missing target now fails.
//
// The workflow also ran this BEFORE "Assemble the site", so _site did not exist
// yet. The step has been moved to after assembly.
//
// Run: node scripts/verify-built.js
const fs = require('fs');
const path = require('path');

const TARGETS = [
  ['DevDojo', 'dist/index.html'],
  ['IdentityDojo', 'identity-dojo/dist/index.html'],
  ['JSDojo', 'js-dojo/dist/index.html'],
  ['MLDojo', 'ml-dojo/dist/index.html'],
  ['fundamentals', 'fundamentals-crash-course/index.html'],
  ['docker', 'docker-crash-course/index.html'],
  ['kubernetes', 'kubernetes-crash-course/index.html'],
  ['envoy', 'envoy-crash-course/index.html'],
  ['istio', 'istio-crash-course/index.html'],
  ['home', 'docs/home.html'],
  ['skills rubric', 'skills-rubric.html'],
];

const ROOT = path.join(__dirname, '..');
const SITE = path.join(ROOT, '_site');

// Everything under _site/ is what actually gets uploaded, so parse all of it.
function walk(dir, out) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walk(full, out);
    else if (e.isFile() && e.name.endsWith('.html')) out.push(full);
  }
  return out;
}

const targets = TARGETS.map(([name, rel]) => [name, rel, true]);
if (fs.existsSync(SITE)) {
  for (const f of walk(SITE, []).sort()) {
    targets.push(['_site ' + path.relative(SITE, f), path.relative(ROOT, f), true]);
  }
} else {
  console.log('  note  _site/ does not exist; only the pre-assembly targets are checked.');
  console.log('        In CI this gate runs AFTER "Assemble the site" and must see _site/.');
}

let failures = 0, checked = 0, missing = 0;

for (const [name, rel] of targets) {
  const file = path.join(ROOT, rel);
  if (!fs.existsSync(file)) {
    console.error(`  MISSING  ${name} (${rel}) — expected to be built by now`);
    missing++; failures++;
    continue;
  }
  const html = fs.readFileSync(file, 'utf8');
  const re = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g;
  let m, blocks = 0, bad = 0;
  while ((m = re.exec(html))) {
    blocks++;
    const body = m[1];
    if (!body.trim()) continue;
    // JSON-LD and similar are data, not code
    const tag = html.slice(m.index, m.index + 120);
    if (/type=["'](application\/(ld\+json|json)|text\/template)["']/.test(tag)) continue;
    checked++;
    try {
      new Function(body);
    } catch (err) {
      bad++; failures++;
      const line = html.slice(0, m.index).split('\n').length;
      console.log(`  FAIL  ${name}: inline script #${blocks} (from line ~${line} of ${rel})`);
      console.log(`        ${err.message}`);
    }
  }
  if (!bad) console.log(`  ok    ${name}: ${blocks} inline block(s) parse`);
}

console.log(`\n${checked} script block(s) checked across ${targets.length} target(s).`);
if (failures) {
  console.error(`\nverify-built FAILED: ${missing} missing target(s), ` +
    `${failures - missing} block(s) that will not parse in a browser.`);
  process.exit(1);
}
console.log('Every built page can run.');
