/* Hand-authored, plain-English quizzes for the concept-heavy identity lessons.
   Attached in boot BEFORE the auto-generated QUIZZES map, so these win (readable
   questions instead of "factorType(\"totp\") returns…?"). Keyed by lesson id. */
window.QUIZZES_HAND = {
  idf0: [
    {q:'What does IdP stand for?',options:['Identity Provider','Internal Data Protocol','Identity Policy','Integrated Directory'],answer:0,why:'The IdP is the authority that authenticates users and issues tokens or assertions.',whyWrong:['','That is not what IdP means.','A policy is a rule set, not the authenticating authority.','A directory stores users; the IdP authenticates them.']},
    {q:'What does OIDC stand for?',options:['OpenID Connect','Open Identity Credential','Online ID Check','OAuth Identity Config'],answer:0,why:'OpenID Connect is the authentication layer built on top of OAuth 2.0.',whyWrong:['','Not a real term.','Not a real term.','Not a real term.']},
    {q:'What does MFA mean?',options:['Multi-Factor Authentication','Managed Federation Access','Multi-Field Authorization','Master File Access'],answer:0,why:'MFA requires two or more independent factors to sign in.',whyWrong:['','Made up.','Made up.','Made up.']},
    {q:'What does SSO mean?',options:['Single Sign-On','Secure Socket Option','Session Storage Object','Signed Security Officer'],answer:0,why:'Single Sign-On lets one login reach many applications.',whyWrong:['','Not a real term.','Not a real term.','Not a real term.']}
  ],
  idffed: [
    {q:'In federation, which party authenticates the user and issues the signed proof?',options:['Identity Provider (IdP)','Relying Party (RP)','The browser','The API gateway'],answer:0,why:'The IdP vouches for the user; everyone else relies on that.',whyWrong:['','The RP relies on the proof, it does not create it.','The browser only carries the proof.','A gateway routes traffic; it does not authenticate the user.']},
    {q:'What does the Service Provider / Relying Party do?',options:['Relies on the IdP proof instead of checking a password','Stores every user password','Signs the token','Runs the MFA prompt'],answer:0,why:'The whole point of federation is that the app trusts the IdP rather than holding passwords.',whyWrong:['','That is what federation avoids.','The IdP signs the token, not the RP.','The IdP handles authentication and MFA.']},
    {q:'Why can a random website not fake "Google says this is you"?',options:['The RP only accepts tokens signed by the pre-trusted IdP key','Google emails a confirmation','Browsers block it','It cannot be prevented'],answer:0,why:'Trust is set up in advance with the IdP public keys, so only real signatures verify.',whyWrong:['','No email is involved in token verification.','The browser does not verify the signature; the RP does.','It absolutely can be prevented by signature verification.']}
  ],
  idffed2: [
    {q:'Which piece is the authority that authenticates users?',options:['Identity Provider (IdP)','Relying Party','Access token','JWKS endpoint'],answer:0,why:'The IdP is the authenticating authority.',whyWrong:['','The relying party consumes the proof.','A token is the proof, not the authority.','JWKS just publishes the keys.']},
    {q:'What is the "proof" passed in federation?',options:['A signed token or assertion','A username and password','A session cookie only','A TLS certificate'],answer:0,why:'The IdP issues a signed token (OIDC) or assertion (SAML) the app can verify.',whyWrong:['','Passwords are what federation avoids sending around.','A cookie tracks a local session, it is not the federated proof.','A certificate proves a server, not the user login.']},
    {q:'Where does the IdP publish the keys used to verify its tokens?',options:['A JWKS endpoint / SAML metadata','Inside the access token','In the user cookie','In the client secret'],answer:0,why:'The IdP publishes public keys at JWKS (OIDC) or in metadata (SAML) so relying parties can verify signatures.',whyWrong:['','The token carries a signature, not the verification key.','Cookies do not carry IdP keys.','The client secret authenticates the app, it is not the IdP signing key.']}
  ],
  am2: [
    {q:'A password is which kind of authentication factor?',options:['Something you know (knowledge)','Something you have (possession)','Something you are (inherence)','Somewhere you are'],answer:0,why:'A password is knowledge — a secret you remember.',whyWrong:['','Possession is a device or key you hold.','Inherence is a biometric.','Location is a context signal, not this factor.']},
    {q:'A one-time code from an authenticator app is which factor?',options:['Something you have (possession)','Something you know','Something you are','A recovery factor'],answer:0,why:'The code comes from a device you possess.',whyWrong:['','Knowledge is a memorized secret.','Inherence is a biometric.','Recovery is a flow, not a factor category.']},
    {q:'A fingerprint is which factor?',options:['Something you are (inherence)','Something you know','Something you have','A knowledge factor'],answer:0,why:'A biometric is inherence — something you are.',whyWrong:['','Knowledge is memorized.','Possession is a held device.','A knowledge factor is a memorised secret, not a biometric.']},
    {q:'True MFA combines factors from…',options:['two or more different categories','two passwords','the same category twice','one strong factor'],answer:0,why:'The categories must differ, so stealing one (a password) is not enough.',whyWrong:['','Two passwords are both knowledge — still one factor type.','Same category twice is not multi-factor.','One factor, however strong, is single-factor.']}
  ],
  am6: [
    {q:'Which NIST scale measures how strongly the real-world identity was proofed at enrollment?',options:['IAL (Identity Assurance Level)','AAL (Authenticator Assurance Level)','FAL (Federation Assurance Level)','TLS level'],answer:0,why:'IAL is about identity proofing.',whyWrong:['','AAL is about login strength, not proofing.','FAL is about how the assertion is protected.','TLS is transport security, not an identity scale.']},
    {q:'Which scale measures how strong the login authentication is?',options:['AAL','IAL','FAL','MFA-2'],answer:0,why:'AAL rates authenticator strength (single factor, MFA, hardware).',whyWrong:['','IAL rates identity proofing.','FAL rates the federated assertion.','Not a real scale.']},
    {q:'MFA corresponds to which authenticator level?',options:['AAL2','AAL1','AAL3','IAL2'],answer:0,why:'AAL2 requires two factors (MFA).',whyWrong:['','AAL1 is a single factor.','AAL3 additionally requires a hardware, phishing-resistant authenticator.','IAL2 is a proofing level, not an authenticator level.']},
    {q:'A hardware, phishing-resistant authenticator (security key) is…',options:['AAL3','AAL1','FAL1','IAL1'],answer:0,why:'AAL3 is the highest authenticator level and requires hardware-backed, phishing-resistant auth.',whyWrong:['','AAL1 is single factor.','FAL is about assertions, not authenticators.','IAL1 is self-asserted identity, unrelated.']}
  ],
  am8: [
    {q:'Creating a new passkey key pair for a site is which WebAuthn ceremony?',options:['Registration (attestation)','Authentication (assertion)','Recovery','Rotation'],answer:0,why:'Registration creates the key pair and may attest the authenticator.',whyWrong:['','Authentication signs a challenge with an existing key.','Recovery is a separate account flow.','Rotation is not a WebAuthn ceremony.']},
    {q:'Signing a server challenge to log in is which ceremony?',options:['Authentication (assertion)','Registration (attestation)','Enrollment','Provisioning'],answer:0,why:'Authentication has the authenticator sign a fresh challenge (an assertion).',whyWrong:['','Registration is the one-time key-pair creation.','Enrollment is another word for registration, not login.','Provisioning creates accounts, not this signature.']},
    {q:'In WebAuthn, the private key…',options:['never leaves the device','is stored on the server','is emailed to the user','is the client secret'],answer:0,why:'The private key stays in the device, which is what makes passkeys phishing-resistant.',whyWrong:['','The server only stores the public key.','Keys are never emailed.','That is an OAuth concept, not a passkey.']}
  ],
  az2: [
    {q:'In RBAC, permissions are granted to a user through…',options:['roles','their IP address','the session id','the request path'],answer:0,why:'Users get roles; roles carry permissions.',whyWrong:['','IP is a network detail, not an RBAC grant.','A session id identifies a login, not permissions.','The path is what is protected, not how access is granted.']},
    {q:'A "viewer" role typically has which permission?',options:['read','read, write, delete','write','admin'],answer:0,why:'A viewer can read only — least privilege.',whyWrong:['','That is an admin-level set.','Viewers do not write.','Admin is the most powerful role, not a viewer.']},
    {q:'Which principle says a role should hold only the access it truly needs?',options:['Least privilege','Separation of duties','Defense in depth','Fail-closed'],answer:0,why:'Least privilege grants the minimum access required.',whyWrong:['','Separation of duties splits conflicting powers between people.','Defense in depth is layered controls.','Fail-closed is a default-deny behavior, not this principle.']}
  ],
  oaclient: [
    {q:'A single-page app (SPA) is which kind of OAuth client?',options:['Public — uses PKCE, no secret','Confidential — uses a client secret','A resource server','An identity provider'],answer:0,why:'A SPA cannot hide a secret, so it is a public client and uses PKCE.',whyWrong:['','It cannot keep a secret, so it is not confidential.','The resource server is the API, not the app.','The IdP is the authority, not the app.']},
    {q:'How does a server-side (confidential) client authenticate to the token endpoint?',options:['With a client secret or a key','With the user password','It cannot authenticate','With a session cookie'],answer:0,why:'Confidential clients prove themselves with a secret or an asymmetric key.',whyWrong:['','The user password is never used by the client this way.','Confidential clients absolutely authenticate.','Cookies are for browser sessions, not client auth.']},
    {q:'Which client authentication method uses no shared secret?',options:['private_key_jwt (asymmetric key)','client_secret_basic','client_secret_post','HTTP Basic with the password'],answer:0,why:'private_key_jwt signs with a private key; the server verifies with the public key — nothing shared to leak.',whyWrong:['','Uses a shared secret.','Uses a shared secret.','Uses a password, the weakest option.']},
    {q:'Where should a client_secret be stored?',options:['A secret manager or server environment, never in front-end code','In the SPA bundle','In the redirect URL','In localStorage'],answer:0,why:'Anything shipped to the browser is public, so secrets stay server-side.',whyWrong:['','The bundle is downloadable by anyone.','URLs get logged and shared.','localStorage is readable by any script (XSS).']}
  ],
  oa10: [
    {q:'Best flow for a web or mobile app acting for a user?',options:['Authorization Code + PKCE','Client Credentials','Implicit','ROPC (password)'],answer:0,why:'Authorization Code with PKCE is the modern default for user-facing apps.',whyWrong:['','Client Credentials is for machines with no user.','Implicit is deprecated.','ROPC (password grant) is deprecated.']},
    {q:'Best flow for machine-to-machine (no user present)?',options:['Client Credentials','Authorization Code','Device flow','Implicit'],answer:0,why:'Client Credentials authenticates the service itself, with no user.',whyWrong:['','Authorization Code needs a user at a browser.','Device flow is for input-limited devices with a user.','Implicit is deprecated and user-facing.']},
    {q:'Which grant is deprecated and should be avoided?',options:['Implicit / ROPC','Authorization Code + PKCE','Client Credentials','Refresh'],answer:0,why:'Implicit and ROPC are discouraged by the OAuth Security BCP.',whyWrong:['','This is the recommended flow.','Still valid for M2M.','Refresh tokens are still used (with rotation).']}
  ],
  s2s6: [
    {q:'Inside a Kubernetes cluster or service mesh, how do services usually prove identity to each other?',options:['mTLS with workload certificates (e.g. SPIFFE/SPIRE)','A shared password in env vars','IP allowlists only','No auth inside the cluster'],answer:0,why:'Each workload gets a short-lived certificate and services verify each other with mutual TLS.',whyWrong:['','Shared static secrets are exactly what this avoids.','IP can be spoofed and is not identity.','Zero trust means never assuming the network is safe.']},
    {q:'Machine-to-machine access to an external API is typically obtained via…',options:['OAuth client-credentials tokens','the user session cookie','a hardcoded API key in the repo','SAML browser SSO'],answer:0,why:'A service gets its own token from a minting authority with the client-credentials grant.',whyWrong:['','There is no user session in M2M.','Hardcoded keys leak and cannot rotate cleanly.','SAML browser SSO needs a human at a browser.']},
    {q:'Zero trust means…',options:['verify identity and authorize every request, regardless of network location','trust anything inside the firewall','trust by IP address','authenticate once at the perimeter only'],answer:0,why:'Never trust by location; authenticate and authorize each call.',whyWrong:['','That is the old perimeter model zero trust replaces.','IP is not identity.','Perimeter-only auth is what zero trust rejects.']}
  ],
  ei2: [
    {q:'In Kerberos, what does the Authentication Service (AS) issue?',options:['A Ticket-Granting Ticket (TGT)','A service ticket','A password','A refresh token'],answer:0,why:'The AS verifies you once and issues a TGT.',whyWrong:['','The TGS issues service tickets, using your TGT.','Passwords are never handed out.','Refresh tokens are an OAuth concept.']},
    {q:'To reach a specific service you present the TGT to the TGS and receive…',options:['a service ticket','another TGT','your password back','a SAML assertion'],answer:0,why:'The TGS grants a per-service ticket so your password never reaches the service.',whyWrong:['','You already have the TGT; the TGS gives a service ticket.','Passwords are not returned.','SAML is a different protocol.']}
  ],
  ei3: [
    {q:'A new hire (Joiner) should trigger which provisioning action?',options:['Create the account','Update access','Deactivate the account','Nothing'],answer:0,why:'Joiner creates the account and grants baseline access.',whyWrong:['','Update is the Mover case.','Deactivate is the Leaver case.','Onboarding must create access.']},
    {q:'An employee who leaves (Leaver) should trigger…',options:['Deactivate/delete the account','Create a new account','Only a password reset','Nothing automatic'],answer:0,why:'Leaver deprovisions access — the biggest security win of automation.',whyWrong:['','That is the Joiner case.','A reset does not remove access.','Leaving accounts active is a top breach cause.']},
    {q:'Which standard automates pushing these create/update/deactivate operations?',options:['SCIM','SAML','OAuth','LDAP browsing'],answer:0,why:'SCIM is the provisioning API that syncs accounts across systems.',whyWrong:['','SAML carries login assertions, not provisioning.','OAuth is authorization for API access.','LDAP is a directory query protocol, not the provisioning push.']}
  ],
  ei4b: [
    {q:'Workforce with an HR system of record is best served by…',options:['SCIM pre-provisioning','JIT only','Manual creation','No provisioning'],answer:0,why:'SCIM keeps accounts in sync from the HR source and supports clean deprovisioning.',whyWrong:['','JIT alone will not deprovision leavers.','Manual does not scale for a workforce.','Some provisioning is required.']},
    {q:'A huge, unpredictable external / customer population is best served by…',options:['JIT provisioning','Pre-importing every user','Manual creation','LDAP sync'],answer:0,why:'JIT creates the account on first login, so you never pre-import millions of users.',whyWrong:['','Pre-importing millions is impractical.','Manual cannot scale to consumers.','LDAP sync fits a directory-backed workforce, not open consumers.']},
    {q:'The classic gap with JIT provisioning is that it…',options:['creates accounts but does not deprovision them','cannot create accounts','requires SAML','is slower than manual'],answer:0,why:'JIT provisions on first login but never removes access, so pair it with SCIM or reviews.',whyWrong:['','Creating accounts is exactly what JIT does.','JIT works with OIDC or SAML.','JIT is far faster than manual.']}
  ],
  biz: [
    {q:'Netflix serving individual consumers is an example of…',options:['B2C','B2B','B2B2C','P2P'],answer:0,why:'Selling directly to individual consumers is B2C.',whyWrong:['','B2B serves other businesses.','B2B2C serves a business that serves its own consumers.','P2P is not a business model here.']},
    {q:'Salesforce serving other companies (each a tenant) is…',options:['B2B','B2C','B2B2C','C2C'],answer:0,why:'Selling to businesses, whose employees are the users, is B2B.',whyWrong:['','B2C is direct-to-consumer.','B2B2C adds the tenant serving its own consumers.','C2C is consumer-to-consumer.']},
    {q:'Shopify (merchants who serve their own shoppers through the platform) is…',options:['B2B2C','B2C','B2B','B2G'],answer:0,why:'You serve a business and, through it, that business own consumers — two identity layers.',whyWrong:['','B2C is direct to consumers only.','B2B stops at the business tenant.','B2G is business-to-government.']},
    {q:'Which models are inherently multi-tenant?',options:['B2B and B2B2C','B2C only','B2C and B2B','none'],answer:0,why:'Serving businesses means each customer is an isolated tenant.',whyWrong:['','B2C is single-population, not tenant-based.','B2C is not multi-tenant.','Multi-tenancy is central to B2B and B2B2C.']}
  ],
  ao3: [
    {q:'PAR (Pushed Authorization Requests) improves security by…',options:['sending the request parameters to the server first, off the browser URL','encrypting the database','rotating refresh tokens','hashing passwords'],answer:0,why:'PAR moves sensitive parameters off the front channel into a back-channel push.',whyWrong:['','Unrelated to database encryption.','That is refresh-token rotation.','That is password storage.']},
    {q:'RAR (Rich Authorization Requests) provides…',options:['fine-grained, structured authorization details beyond coarse scopes','a faster token endpoint','a new password hash','mutual TLS'],answer:0,why:'RAR replaces blunt scopes with structured detail like "transfer up to 500 from account X".',whyWrong:['','It is about detail, not speed.','Nothing to do with passwords.','mTLS is a client-auth mechanism, not RAR.']},
    {q:'DPoP is about…',options:['sender-constrained (proof-of-possession) tokens','compressing tokens','user consent screens','password storage'],answer:0,why:'DPoP binds a token to a key the client must prove, so a stolen token is useless.',whyWrong:['','Not compression.','Not consent.','Not password storage.']}
  ],
  ao5: [
    {q:'Which defense stops CSRF on the OAuth redirect?',options:['The state parameter','A nonce','PKCE','Exact redirect_uri matching'],answer:0,why:'The state parameter is a random value the client checks on return, blocking CSRF.',whyWrong:['','nonce defends ID-token replay, not the redirect CSRF.','PKCE defends code interception.','Exact redirect_uri defends open redirect / mix-up.']},
    {q:'Which defends against authorization-code interception by public clients?',options:['PKCE','state','nonce','CORS'],answer:0,why:'PKCE ties the code to a secret only the real client holds, so a stolen code is useless.',whyWrong:['','state defends CSRF.','nonce defends replay of ID tokens.','CORS is a browser policy, not this defense.']},
    {q:'Which defends against replay of a token or ID token?',options:['A one-time nonce','state','exact redirect_uri','a longer secret'],answer:0,why:'A nonce (plus short expiry) makes a captured token single-use.',whyWrong:['','state defends CSRF on the redirect.','redirect_uri matching defends open redirect.','Length alone does not stop replay.']},
    {q:'Open redirect / mix-up is mitigated by…',options:['registering and matching exact redirect_uri values','wildcards in redirect_uri','longer tokens','disabling PKCE'],answer:0,why:'Only exact, pre-registered redirect URIs should be accepted.',whyWrong:['','Wildcards are the vulnerability, not the fix.','Token length is unrelated.','Disabling PKCE weakens security.']}
  ],
  ig5: [
    {q:'CIAM (Customer IAM) primarily serves…',options:['customers / consumers','employees','service accounts','admins only'],answer:0,why:'CIAM is about external consumers, optimizing self-service and scale.',whyWrong:['','Employees are workforce IAM.','Service accounts are machine identity.','Admins are a small subset, not the focus.']},
    {q:'Workforce IAM primarily serves…',options:['employees and contractors','external customers','the public','IoT devices'],answer:0,why:'Workforce IAM governs staff, emphasizing control and deprovisioning.',whyWrong:['','Customers are CIAM.','The public is CIAM territory.','Devices are workload/machine identity.']}
  ],
  idcap: [
    {q:'In the auth lifecycle, the "register" step should…',options:['hash the password (never store plaintext)','issue tokens','revoke the session','validate a token'],answer:0,why:'Registration stores a slow, salted hash of the password.',whyWrong:['','Issuing tokens happens at login.','Revoking is logout.','Validation happens on each request.']},
    {q:'On "login", the server…',options:['issues tokens (access + refresh)','hashes the password','deletes the account','rotates signing keys'],answer:0,why:'After verifying credentials, login mints the tokens.',whyWrong:['','Hashing is a registration step.','Login does not delete anything.','Key rotation is an operational task, not login.']},
    {q:'On each "request", the server…',options:['validates the access token, then authorizes the action','re-hashes the password','issues a new refresh token','creates the account'],answer:0,why:'Every request checks the token (iss/aud/exp) and then the permission.',whyWrong:['','No password is involved per request.','Refresh happens on the refresh endpoint, not every request.','The account already exists.']},
    {q:'On "logout", the server…',options:['revokes the session','issues a token','hashes a password','creates a session'],answer:0,why:'Logout must end the session server-side, not just drop the cookie.',whyWrong:['','Tokens are issued at login.','Hashing is registration.','Creating a session is login.']}
  ],
  am9: [
    {q:'Where do most account breaches actually come from?',options:['Credential stuffing (replaying passwords leaked elsewhere)','Zero-day exploits','Tricking admins in person','Brute-forcing strong passwords'],answer:0,why:'Attackers replay username/password pairs leaked from other sites, betting on reuse — cheap and automated.',whyWrong:['','Zero-days are rare and expensive next to stuffing.','That happens but is not the bulk of takeovers.','Brute-forcing strong passwords is slow and usually rate-limited.']},
    {q:'Which single control makes a leaked password insufficient on its own?',options:['MFA','A longer password policy','Security questions','Login email notifications'],answer:0,why:'With MFA, a correct-but-leaked password still cannot complete the login.',whyWrong:['','Length does not help once the exact password has leaked.','Knowledge answers are also leakable and guessable.','Notifications warn after the fact; they do not block.']},
    {q:'Checking a new password against known-breached lists is done safely with…',options:['k-anonymity (only a hash prefix leaves you)','sending the full password to a third party','downloading every breach in full','an email round-trip'],answer:0,why:'Services like Have I Been Pwned use k-anonymity, so the password itself never leaves your server.',whyWrong:['','You must never send the full password.','Impractical and unnecessary.','Unrelated to breach checks.']},
    {q:'A flood of failed logins across many accounts is best stopped by…',options:['rate limiting + bot detection','a CAPTCHA on every page','taking the site offline','longer sessions'],answer:0,why:'Throttle the automation and detect bots; keep humans unblocked.',whyWrong:['','CAPTCHA everywhere punishes real users — a last resort.','That is denial of service to yourself.','Unrelated to the attack.']}
  ],
  iddid: [
    {q:'In decentralized identity, where do your credentials live?',options:['In your own wallet','On a central IdP server','In a shared database','Only in the browser cache'],answer:0,why:'The holder keeps Verifiable Credentials in a wallet and presents them directly.',whyWrong:['','There is no central IdP mediating each sign-in.','They are not held in a shared database.','A wallet is durable storage, not just cache.']},
    {q:'A Verifiable Credential is…',options:['a signed, tamper-evident claim issued by an authority','a username and password','a session cookie','an IP allowlist'],answer:0,why:'A VC is a cryptographically signed claim (e.g. "over 18") you can present and others can verify.',whyWrong:['','It is not a password-style credential.','A cookie is a local session token.','Unrelated to VCs.']},
    {q:'Selective disclosure lets you…',options:['prove you are over 18 without revealing your birthdate','share your whole profile at once','skip verification entirely','reset your password'],answer:0,why:'Selective disclosure / zero-knowledge proofs reveal only the fact needed, nothing more.',whyWrong:['','That is the opposite of the goal.','Verification still happens on the disclosed fact.','Unrelated.']},
    {q:'Compared with federation, decentralized identity…',options:['has no central IdP that sees every login','still requires a central IdP','cannot be verified without the issuer online','is exactly the same thing'],answer:0,why:'No central authority mediates each sign-in, which improves privacy and resilience.',whyWrong:['','It removes the central IdP.','A verifier checks the signature without contacting the issuer.','It is a distinct model from federation.']}
  ],
  igaudit: [
    {q:'To prove who did what and when, you need…',options:['an immutable audit log','more RAM','a faster CPU','a bigger cache'],answer:0,why:'An append-only, tamper-evident audit trail is the evidence auditors and investigators need.',whyWrong:['','Hardware does not make actions provable.','Speed is unrelated to auditability.','Caching is unrelated.']},
    {q:'Real-time detection of suspicious login patterns is the job of…',options:['a SIEM','the password hasher','the stylesheet','the DNS resolver'],answer:0,why:'A SIEM ingests the logs and alerts on patterns like failed-login bursts or a new admin.',whyWrong:['','Hashing protects stored passwords, not detection.','Unrelated.','Unrelated.']},
    {q:'Which must NEVER appear in identity logs?',options:['full tokens or secrets','the user id','the timestamp','the action name'],answer:0,why:'Logging secrets or full tokens turns your logs into a breach; log identifiers and metadata only.',whyWrong:['','The subject id is expected and useful.','Timestamps are required.','The action is the whole point of the log.']},
    {q:'Frameworks like SOC 2 and NIST 800-63 map their controls to identity practices such as…',options:['MFA, least privilege, deprovisioning, audit logs','screen colors','marketing copy','the database vendor'],answer:0,why:'Those frameworks require exactly these identity controls, evidenced by your audit trail.',whyWrong:['','Not a security control.','Not a control.','Not a control.']}
  ],
  idflife: [
    {q:'Identity proofing happens at which point?',options:['Every time the user logs in','Once, before the account exists','Only when the password is reset','Never, it is automatic'],answer:1,why:'Proofing establishes who the person is in the real world, before an account is created. Authentication is the repeated step afterwards.',whyWrong:['That is authentication — proofing is not repeated per login.','','A reset re-binds a credential; it does not re-establish the real-world identity.','It is a deliberate process, not something that happens by itself.']},
    {q:'What is the difference between an authenticator and a credential?',options:['They are two words for the same thing','An authenticator is the thing you hold; a credential is the stored binding to your identifier','A credential is always a password','An authenticator is always hardware'],answer:1,why:'You possess an authenticator (password, passkey, security key); the system stores a credential recording that it belongs to your account.',whyWrong:['They are distinct — NIST separates them precisely because the attacks differ.','','A password is one kind of authenticator; a credential is the stored binding.','Authenticators can be knowledge or biometric, not just hardware.']},
    {q:'An organisation fails an audit for accounts belonging to people who left years ago. Which lifecycle step broke?',options:['Deprovisioning','Identity proofing','Credential binding','Authentication'],answer:0,why:'Deprovisioning — the leaver step — is the one most often skipped, leaving orphaned accounts with live access.',whyWrong:['','Proofing was fine; these were real employees.','Binding worked; that is why the accounts still function.','Authentication is working correctly, which is exactly the problem.']},
    {q:'Why should an application key its user records on a stable internal id rather than an email address?',options:['Emails are too long to index','Email addresses can change or be reassigned to a different person','Emails are encrypted','It makes no practical difference'],answer:1,why:'An identifier that can be reassigned will eventually attach one person’s history to another.',whyWrong:['Length is not the issue.','','Emails in a directory are not encrypted, and that would not help.','It matters a great deal, usually discovered years later.']},
    {q:'One person has a work account, a Google account and a customer account at the same shop. How many people is that?',options:['Three','One person with three accounts','Three identities and no person','It depends on the protocol'],answer:1,why:'A person is not an account. One human routinely holds many accounts, each with its own identifier.',whyWrong:['Accounts are not people; conflating them is the mistake this lesson exists to prevent.','','There is very much a person; the accounts describe them.','The distinction holds regardless of protocol.']}
  ],
  idfclaim: [
    {q:'What turns a stored attribute into a claim?',options:['Encrypting it','Being asserted by a specific issuer, in transit','Storing it in a directory','Adding it to a database index'],answer:1,why:'An attribute is a fact at rest; it becomes a claim when an issuer asserts it to someone else.',whyWrong:['Encryption changes who can read it, not what kind of fact it is.','','That is what makes it an attribute in the first place.','Indexing is a storage detail.']},
    {q:'Which claim should an application treat as the identity of the user?',options:['email','sub','name','preferred_username'],answer:1,why:'sub is immutable and scoped to the issuer, so it never gets reassigned to a different person.',whyWrong:['Email addresses get changed and reused.','','Names are not unique and change frequently.','A username can be released and reassigned.']},
    {q:'What does the aud claim tell a verifier?',options:['Who this token is intended for','Who issued the token','When it expires','Which algorithm signed it'],answer:0,why:'aud names the intended recipient. A token minted for a different API is not valid for yours.',whyWrong:['','That is iss.','That is exp.','That is alg, in the header.']},
    {q:'An IdP issues a token claiming "role":"admin", but roles are defined by your application. What should you conclude?',options:['The user is an admin; the signature is valid','The claim is only as good as the issuer authority over that fact','Any signed claim must be honoured','The token is forged'],answer:1,why:'A valid signature proves who said it, not that they had any business saying it. Trust an issuer only for facts it is authoritative over.',whyWrong:['A valid signature does not confer authority over your application concepts.','','Honouring every signed claim is how privilege escalation happens.','Nothing suggests forgery — the problem is authority, not authenticity.']},
    {q:'Why do federation integrations often authenticate successfully but create broken user records?',options:['Expired certificates','Mismatched attribute mapping between the IdP and the app','Slow networks','Weak passwords'],answer:1,why:'Every system names attributes differently, and a wrong mapping still passes signature checks — the login works, the data lands in the wrong fields.',whyWrong:['An expired certificate breaks the login itself, not just the record.','','Latency does not corrupt records.','Passwords are not involved in a federated login.']}
  ],
  idftok: [
    {q:'What is a token, in one sentence?',options:['An encrypted password','A string standing for a verified fact, issued by an authority and presented later','A type of cookie','A hashing algorithm'],answer:1,why:'You prove yourself once and receive a string you present instead of proving yourself again.',whyWrong:['A token is not a password in any form; that is the point of it.','','A cookie is one way to carry a token, not what a token is.','Hashing is a technique used inside tokens, not the token itself.']},
    {q:'What makes a token "opaque"?',options:['It is encrypted','It carries no readable meaning and must be looked up at the issuer','It is very short','It cannot expire'],answer:1,why:'An opaque token is a random lookup key; the real data stays in the issuer store.',whyWrong:['Encryption is a different thing — an opaque token is usually just random.','','Length is incidental, though they do tend to be shorter.','Opaque tokens expire too, and can also be revoked instantly.']},
    {q:'Can anyone who intercepts a JWT read its claims?',options:['Yes — base64url is encoding, not encryption','No, the signature encrypts the payload','Only with the private key','Only if alg is none'],answer:0,why:'The payload is merely base64url-encoded. The signature prevents tampering, not reading.',whyWrong:['','A signature authenticates; it does not conceal.','No key is needed to decode; that is what JWE is for.','The alg value has nothing to do with readability.']},
    {q:'"Access token" and "JWT" describe…',options:['The same thing','A role and a format — which vary independently','Two competing standards','Two parts of the same token'],answer:1,why:'Access token is the job the token does; JWT is how the bytes are arranged. An access token may be a JWT or opaque.',whyWrong:['They answer different questions entirely.','','They are not alternatives to each other.','A JWT is not a component of an access token.']},
    {q:'Why is revocation harder with a structured token than an opaque one?',options:['Structured tokens are longer','There is no central record to delete — it stays valid until it expires','Structured tokens are not signed','Opaque tokens never expire'],answer:1,why:'Self-contained tokens verify offline, so nothing central exists to invalidate. Short lifetimes plus refresh are the industry patch.',whyWrong:['Size affects bandwidth, not revocability.','','They are signed; that is what makes them verifiable offline.','They do expire; they are also revocable, which is their advantage.']},
    {q:'A verifier reads the alg field from the token header and uses whatever it says. What is the flaw?',options:['It is slow','An attacker can propose alg:none and talk it out of verifying','alg is optional','It only works with RSA'],answer:1,why:'The algorithm must be pinned by the verifier in advance, never chosen by the token being checked.',whyWrong:['Performance is not the concern.','','alg is present; the problem is obeying it.','The flaw applies to every algorithm.']}
  ],
  idfcast: [
    {q:'SAML says "Service Provider". What does OAuth/OIDC call the same box?',options:['Client (or Relying Party)','Authorization Server','Resource Server','Subject'],answer:0,why:'The app relying on someone else authentication is the SP in SAML and the client/RP in OIDC.',whyWrong:['','That is the IdP counterpart — the authority.','That is the protected API, which SAML has no equivalent for.','That is the person.']},
    {q:'Who is the "resource owner" in OAuth?',options:['The API holding the data','The person who owns the data and can authorise access to it','The company running the server','The client application'],answer:1,why:'The resource owner is the user whose data is at stake, and therefore the only one who can grant an app access to it.',whyWrong:['That is the resource server.','','Ownership here is about the data subject, not the operator.','The client is the app requesting access.']},
    {q:'Which actor is the only one that mints tokens?',options:['The client','The resource server','The authorization server','The browser'],answer:2,why:'The authority issues tokens; clients present them and resource servers verify them.',whyWrong:['A client receives and presents tokens.','A resource server verifies and consumes them.','','The browser only carries them.']},
    {q:'"Authenticate the client" means…',options:['Prove which application is calling','Prove which person is logged in','Check the user password','Verify the token signature'],answer:0,why:'A client is a registered application with its own identity, separate from the user identity.',whyWrong:['','That is authenticating the user — a different question in the same flow.','Passwords belong to users, not clients.','Signature verification is a separate step.']},
    {q:'How does an application learn an OIDC authority signing keys?',options:['They are embedded in the access token','From the discovery document jwks_uri','The user supplies them','They are derived from the client secret'],answer:1,why:'The authority publishes /.well-known/openid-configuration, which points at the JWKS holding its public keys.',whyWrong:['A token carries a signature, not the key needed to check it.','','Users are never involved in key distribution.','A client secret authenticates the app; it is unrelated to the issuer signing key.']}
  ],
  idf3: [
    {q:'Single Sign-On is best described as…',options:['A protocol','A user experience: one login event, many applications','An encryption standard','A type of token'],answer:1,why:'SSO names an outcome the user perceives. It specifies no messages or actors, and can be produced several different ways.',whyWrong:['There is no "SSO protocol" — SAML and OIDC are protocols that can produce it.','','Nothing about SSO is an encryption scheme.','SSO is not a token; tokens are one means to the end.']},
    {q:'Several apps under the same domain share one session cookie, so logging into one logs you into all. Is that SSO?',options:['Yes, and it needs no federation at all','No, SSO requires an IdP','No, SSO requires SAML or OIDC','Only if a token is involved'],answer:0,why:'It is genuine SSO — one login, many apps — achieved with cookie scope alone. This is why "we need SSO" must be followed by "across what boundary?"',whyWrong:['','An IdP is needed for federated SSO, not for SSO as such.','Those are needed to cross an organisational boundary, not to achieve the experience.','A session cookie is enough; no token is required.']},
    {q:'An organisation federates exactly one application. What do they gain?',options:['Nothing, since there is no sign-on-once benefit','Central MFA and policy, instant deprovisioning, and no password stored in the app','Only faster logins','Only a nicer login page'],answer:1,why:'The structural wins are the point of federation; SSO is the side effect that appears once you federate a second app.',whyWrong:['The SSO benefit is absent, but the architectural benefits are not.','','Federation usually adds a redirect, so it is not about speed.','Appearance is incidental.']},
    {q:'Why is using an OAuth access token as proof of who the user is a vulnerability?',options:['Access tokens expire too quickly','An access token authorises an app to call an API; it makes no reliable statement about the user','Access tokens are unsigned','It is not a problem'],answer:1,why:'OAuth answers "may this app do this?" not "who are you?" — OpenID Connect adds the ID token precisely to answer the second question.',whyWrong:['Expiry is unrelated to the confusion.','','Many are signed; signing does not make them identity statements.','It is a well-documented class of vulnerability.']},
    {q:'What distinguishes delegation from impersonation?',options:['Delegation is faster','Delegation records both the app and the user; impersonation makes the app indistinguishable from the user','Impersonation is always malicious','They are the same thing'],answer:1,why:'In delegation the API can see a client acting for a user. In impersonation it sees only the user, which is more powerful and harder to audit.',whyWrong:['Speed is not the difference.','','Impersonation is a legitimate, deliberate pattern — it just needs care.','They are formalised as distinct modes in token exchange.']},
    {q:'Why is Single Logout so much less reliable than Single Sign-On?',options:['Logout messages are not encrypted','The single login actually created many separate application sessions, and there is no reliable way to close them all','Browsers block logout','Logout is not part of any spec'],answer:1,why:'SSO is a pleasant illusion over N real sessions; ending one does not end the rest.',whyWrong:['Encryption is not the obstacle.','','Browsers do not block logout requests.','SLO is specified; it is the distributed state that makes it fragile.']}
  ],
  idfdauthn: [
    {q:'In a design review, which single question tells you whether an integration is credential forwarding or federation?',options:['Which protocol version is used','Where does the user type their password','How long the token lasts','Whether TLS is enabled'],answer:1,why:'If the password is typed into a form your application renders, you are forwarding credentials, whatever the diagram claims.',whyWrong:['Version numbers say nothing about credential exposure.','','Lifetime is a token property, not a credential-path property.','TLS protects transport; the app still holds the password.']},
    {q:'An app collects the username and password and performs an LDAP bind to verify them. What is the main security consequence?',options:['The app is inside the credential blast radius','LDAP is unencrypted','Passwords cannot be hashed','Nothing, this is the modern default'],answer:0,why:'The application holds plaintext passwords in memory and logs, so compromising the app compromises every password typed into it.',whyWrong:['','LDAP can run over TLS; that is a separate concern.','The directory still hashes them; exposure is at the app.','It is a legacy pattern, deprecated wherever a browser exists.']},
    {q:'Why can credential forwarding not support passkeys or SSO?',options:['They require newer Java versions','The authority never interacts with the user directly, and no reusable login session is created','Passkeys need a password first','Both are proprietary'],answer:1,why:'Passkeys need the authenticator to talk to the authority, and SSO needs a session at the authority for a second app to reuse. Forwarding creates neither.',whyWrong:['Runtime versions are irrelevant.','','Passkeys replace passwords rather than supplementing them.','Both are open standards.']},
    {q:'Which delegated-authentication method is still defensible today?',options:['ROPC for new web apps','Credential forwarding for legacy protocols with no browser, such as IMAP or LDAP clients','Embedded webviews showing the IdP login','Any method, if TLS is used'],answer:1,why:'Protocols with no browser cannot redirect. The mitigations are app-specific passwords or moving the protocol onto OAuth with SASL.',whyWrong:['ROPC is deprecated by the security BCP.','','A webview lets the host app read what is typed — forwarding with extra steps.','TLS protects the wire, not the app holding the password.']},
    {q:'Someone says "we delegate authentication to Okta." What do they almost certainly mean?',options:['Federation — the user authenticates at Okta and the app receives a signed assertion','Okta stores their password file','The app posts passwords to an Okta API','Okta issues them certificates'],answer:0,why:'Both are literally delegated authentication, but the redirect style is what people mean, and it is the one that keeps the app out of the blast radius.',whyWrong:['','A password file is not how any of this works.','That would be credential forwarding, which is the pattern to avoid.','Certificates are a different mechanism.']}
  ],
  idfdauthz: [
    {q:'Before OAuth, an app needing your cloud photos asked for your cloud password. Which problem does delegated authorization NOT solve?',options:['Unlimited scope of access','Access that never expires','No way to revoke one app','The need to authenticate at all'],answer:3,why:'Delegation bounds, expires and revokes app access — but somebody still has to authenticate the user first.',whyWrong:['Scopes bound it.','exp expires it.','Revoking the grant removes one app.','']},
    {q:'What is the difference between revoking a token and revoking a grant?',options:['They are identical','A token is one credential; the grant is the recorded permission, so revoking it also stops refreshes','Grants cannot be revoked','Tokens last longer than grants'],answer:1,why:'"Remove this app access" means deleting the grant, otherwise the refresh token quietly mints new access tokens.',whyWrong:['They operate at different levels.','','Grants are exactly what the user removes.','Grants outlive tokens, not the reverse.']},
    {q:'A token carries scope photos:read. Ada uses it to request Bob photos. What should happen?',options:['Allowed, the scope is present','Denied, because a scope bounds the app but the user rights still apply','Allowed if Bob account is public','Denied, because photos:read is read-only'],answer:1,why:'Both checks must pass: what the app was allowed to ask for, and what the user is actually allowed to see. Treating a scope as the whole decision is a real vulnerability.',whyWrong:['The scope is necessary, not sufficient.','','Ownership rules are not waived by a scope.','Read-only is not the reason; the reason is ownership.']},
    {q:'What should a resource server do when the scope claim is missing or unparseable?',options:['Allow the request','Deny the request','Assume the default scope','Retry without the token'],answer:1,why:'Fail closed. An absent scope claim means no permissions, never full permissions.',whyWrong:['Failing open is how absent claims become privilege escalation.','','There is no safe default to assume.','Retrying unauthenticated is worse.']},
    {q:'Why is accepting an OAuth access token as proof of who the user is exploitable?',options:['Access tokens are unsigned','It authorises an app to call an API and makes no reliable statement about the user, and may have been obtained for someone else','They expire too fast','They are too long'],answer:1,why:'OAuth answers "may this app do this?" OpenID Connect adds the ID token to answer "who is this?"',whyWrong:['Many are signed; signing does not make them identity statements.','','Expiry is unrelated.','Size is irrelevant.']}
  ],
  idfobo: [
    {q:'A gateway forwards the user original token unchanged to a downstream service. What breaks?',options:['Nothing, this is standard','Every service must ignore the audience check, so one token now works everywhere','The token gets too large','The signature becomes invalid'],answer:1,why:'The aud names the first service. Accepting it downstream means abandoning audience validation, which turns the token into a universal key.',whyWrong:['It is a common shortcut and a known anti-pattern.','','Forwarding does not change the size.','The signature is still valid — that is what makes it tempting.']},
    {q:'What distinguishes delegation from impersonation in a token?',options:['Delegation records the acting party in an act claim; impersonation shows only the user','Delegation is encrypted','Impersonation tokens are shorter','They are the same'],answer:0,why:'With an act claim the downstream can see "service X acting for user Y". Impersonation loses the acting party entirely.',whyWrong:['','Encryption is unrelated.','Size is not the distinction.','Token exchange formalises them as distinct modes.']},
    {q:'What is the may_act claim for?',options:['Naming who is permitted to act for this subject','Setting the token expiry','Listing the allowed scopes','Naming the issuer'],answer:0,why:'may_act gates delegation: it names which party may exchange this token to act on the subject behalf.',whyWrong:['','That is exp.','That is scope.','That is iss.']},
    {q:'Why is passing X-User-Id: ada between services not an acceptable substitute for a token?',options:['Headers are size-limited','It is unauthenticated, so any service that can reach the endpoint can claim to be anyone','Headers are not logged','It is slower than a token'],answer:1,why:'A token is signed, so the downstream verifies the claim instead of trusting the caller. An unauthenticated header makes security depend entirely on perfect network isolation.',whyWrong:['Size is not the problem.','','Logging is not the problem either.','It is faster, and that is exactly the trap.']},
    {q:'In a four-hop chain, what must be true of the token at each hop?',options:['It must be the same token throughout','Each hop needs its own audience, while the subject survives and the acting party is recorded','Only the last hop needs a token','Each hop should mint its own unsigned token'],answer:1,why:'Audience-per-hop preserves the point of audience validation; the subject and act claims preserve authorization and attribution.',whyWrong:['That is the forwarding anti-pattern.','','Every hop is a checkpoint.','Unsigned tokens are not tokens.']}
  ],
  idfactas: [
    {q:'What is the core modelling mistake in a "view as this user" feature?',options:['Using cookies','Collapsing the two subjects — minting the customer a session instead of keeping both identities','Not encrypting the session','Making it too slow'],answer:1,why:'With one subject the audit log says the customer acted. Keeping the authenticated subject and the effective subject separate is what makes everything else possible.',whyWrong:['Cookies are fine as a transport.','','Encryption does not restore attribution.','Performance is not the risk.']},
    {q:'What permissions should an acting-as session have?',options:['The target permissions','The union of both','The intersection of both, and usually less','Whatever the engineer normally has'],answer:2,why:'If acting-as adopted the target rights, acting as an admin would hand the engineer admin. Intersect, then narrow further.',whyWrong:['That is the escalation path.','A union is strictly worse.','','Then it would not show what the customer sees.']},
    {q:'Which action should stay denied in an acting-as session even when writes have been approved?',options:['Viewing an order','Changing the account email address','Reading a support note','Viewing configuration flags'],answer:1,why:'Changing email, changing the password, adding MFA factors, deleting the account and exporting data are all account-takeover primitives.',whyWrong:['A read, and the normal case.','','Also a read.','Also a read.']},
    {q:'Why must an acting-as session show a persistent banner?',options:['To satisfy branding','Because engineers forget which window they are in and act on production data believing it is their own account','To slow them down','Because the spec requires it'],answer:1,why:'It is a human-factors control, and a cheap one relative to the mistake it prevents.',whyWrong:['Not a branding matter.','','Friction is not the goal.','No spec mandates it; the risk does.']},
    {q:'A customer reports a rendering bug. Which option should you reach for first?',options:['Full write acting-as','A diagnostics or redacted view showing their config and screens without their content','Ask for their password','Impersonate them silently'],answer:1,why:'Take the lowest rung of the ladder that solves the problem — and if it fits, ask the user to screen-share, which is consent given directly.',whyWrong:['The highest-risk option for a read-only problem.','','Never ask for a password.','Silent impersonation destroys attribution.']}
  ],
  idfzt: [
    {q:'What did the perimeter model treat as authorization?',options:['Being inside the network','A signed token','A password','A certificate'],answer:0,why:'Authenticate once at the edge, then trust anything inside. One phished laptop puts the attacker inside, where nothing checks anything.',whyWrong:['','Tokens are the zero-trust answer, not the perimeter one.','A password was the edge check, not the interior one.','Certificates came later.']},
    {q:'"Never trust, always verify" — what does always mean here?',options:['Once per login','Once per session','Every request','Once per day'],answer:2,why:'Every request re-establishes who is asking and whether they may. Signed, audience-scoped, short-lived tokens are what make that cheap.',whyWrong:['That is the perimeter model.','Per-session is still a long window for a revoked user.','','Daily is not verification.']},
    {q:'A request arrives from 10.0.0.5, an internal address. How much should that contribute to the access decision?',options:['It should be trusted as identity','It is context at most, never identity','It should be denied outright','It should skip authentication'],answer:1,why:'An IP is a routing detail that can be spoofed, reassigned or shared. Context is evidence feeding a decision, never a reason to skip one.',whyWrong:['That is precisely the perimeter assumption.','','Internal addresses are not inherently suspicious either.','Skipping authentication is the failure mode.']},
    {q:'The policy decision point is unreachable. What should the enforcement point do?',options:['Permit, to avoid an outage','Deny','Cache the last decision indefinitely','Permit reads only'],answer:1,why:'Fail closed. A system that fails open under load is one an attacker will deliberately overload.',whyWrong:['Failing open to protect availability hands an attacker a way in: overload the policy engine, then walk through.','','Indefinite caching is failing open slowly — revoked access keeps working.','Reads still disclose data, so this is not a safe middle ground.']},
    {q:'Which statement about zero trust is accurate?',options:['It is a product you can buy','It means MFA everywhere','It is an architecture where identity, not network location, is what access decisions are made on','It means trusting nothing at all'],answer:2,why:'Trust is still granted constantly — it is just explicit, narrow, evidenced and short-lived rather than implied by a network cable.',whyWrong:['Vendors sell components, not the architecture.','MFA at the edge with a flat interior is still the perimeter model.','','The name is unhelpful; verification, not absence of trust, is the point.']}
  ],
  idfapikey: [
    {q:'What is an API key, precisely?',options:['A long-lived opaque bearer token identifying an application','A signed token identifying a user','An encrypted password','A short-lived session cookie'],answer:0,why:'Every word matters: long-lived, opaque, bearer, and it names an application rather than a person.',whyWrong:['','There is no user in the picture at all.','It is not derived from a password.','Sessions expire; keys usually never do.']},
    {q:'Why should an API key never travel in a URL query string?',options:['Query strings have a length limit','URLs land in access logs, browser history and Referer headers sent to third parties','Query strings are not encrypted by TLS','It is slower than a header'],answer:1,why:'A key in a URL has already been copied into infrastructure that assumes URLs are not secret.',whyWrong:['Length is not the issue.','','TLS does encrypt the URL in transit; the leak is at the endpoints.','Performance is irrelevant.']},
    {q:'Why give every issued key an identifiable prefix such as sk_live_?',options:['It makes the key longer and harder to brute force','Secret scanners can spot a leaked key in a public repo and alert you','It encrypts the key','It is required by the HTTP spec'],answer:1,why:'The prefix costs nothing and turns a silent leak into an alert, and it tells an engineer at a glance what they are holding.',whyWrong:['A prefix is public and adds no entropy.','','A prefix does not encrypt anything.','No spec requires it.']},
    {q:'How should API keys be stored on the server?',options:['Encrypted with a reversible key','Hashed, like passwords','In plaintext, so support can read them out','In an environment variable'],answer:1,why:'Show the plaintext once at creation and store only a hash, so the database never contains a usable credential.',whyWrong:['Reversible encryption means a database breach is still a credential breach.','','If support can read it, so can an attacker with the same access.','That is where the client keeps it, not the issuer.']},
    {q:'Where are API keys genuinely the wrong tool?',options:['A webhook receiver','A nightly CI job','Anywhere a user is involved, or where the code runs somewhere the user can read it','An internal script'],answer:2,why:'A key cannot represent a user, and a key shipped in a mobile app or SPA bundle is not a secret at all.',whyWrong:['A classic good fit.','Also a good fit, though federation is better still.','','Also a good fit.']}
  ],
  idfcapurl: [
    {q:'What defines a capability URL?',options:['It is very long','The URL itself is the credential — holding the link is the authorization','It requires a session cookie','It uses a special HTTP method'],answer:1,why:'No session and no token header: possession of the unguessable link is the whole authorization.',whyWrong:['Length is incidental.','','If it needed a session it would not be a capability URL.','It is an ordinary GET or POST.']},
    {q:'A password reset link is consumed before the user ever clicks it. What is the most likely cause?',options:['The user clicked twice','A corporate mail security gateway fetched the link to scan it','The token expired','The email was encrypted'],answer:1,why:'Scanners visit links to check for malware, which consumes a single-use GET. Requiring a POST to consume the token avoids it.',whyWrong:['Possible but far less common than scanning.','','Expiry produces a different error, not a consumed token.','Encryption does not follow links.']},
    {q:'Why is Referrer-Policy relevant to capability URLs?',options:['It compresses the URL','If the page links to or loads anything external, the full capability URL can be sent to that third party','It expires the link','It signs the URL'],answer:1,why:'The Referer header carries the whole URL, secret included. Set no-referrer on capability pages.',whyWrong:['It does no compression.','','Expiry is a server concern.','It provides no signature.']},
    {q:'What is the trade-off between a stored capability and a signed one?',options:['Stored is revocable but needs a lookup; signed is stateless but cannot be revoked before expiry','Signed links are always more secure','Stored links cannot expire','There is no difference'],answer:0,why:'It is the opaque-versus-structured token trade-off appearing again, this time in a URL.',whyWrong:['','Neither is universally more secure; they fail differently.','Stored links expire perfectly well.','The revocation behaviour differs sharply.']},
    {q:'What should be logged when a capability URL is used?',options:['The full URL, for debugging','Only a short prefix identifying which capability was used','Nothing at all','The user password'],answer:1,why:'A prefix is enough to correlate the use in an audit trail without turning your logs into a credential store.',whyWrong:['That copies a working credential into your logs.','','You still need an audit trail.','Passwords are not involved.']}
  ],
  idfassume: [
    {q:'A role has two policies. What does the trust policy control?',options:['What the role can do once assumed','Who is allowed to assume the role','How long the credential lasts','Which region it works in'],answer:1,why:'The trust policy is an identity question; the permission policy is the authorization question.',whyWrong:['That is the permission policy.','','Duration is a separate parameter.','Not a policy concern.']},
    {q:'A SaaS vendor is trusted by many customers. Why is an external id needed?',options:['To identify the vendor','Because being trusted by everyone means any customer could otherwise aim the vendor at another customer role','To encrypt the request','To speed up assumption'],answer:1,why:'The confused deputy: customer B names A role, and the vendor account genuinely is trusted by A, so the call succeeds. A per-customer secret breaks it.',whyWrong:['The account id already does that.','','It provides no encryption.','It has no performance role.']},
    {q:'A cloud trust policy names the CI provider as OIDC issuer but places no condition on the sub claim. What is the consequence?',options:['Nothing, the issuer check is sufficient','Any repository on that CI platform can assume the role','Only private repositories can assume it','The role cannot be assumed at all'],answer:1,why:'The issuer check proves the token is real; the subject check proves it is the right one. You need both, exactly as with iss and aud.',whyWrong:['The issuer vouches for every one of its tenants, not just yours.','','Visibility is irrelevant to the trust policy.','It can be assumed — that is the problem.']},
    {q:'What does workload identity federation remove?',options:['The need for any authorization','The long-lived static credential that role assumption otherwise needs to start from','The audit trail','The role itself'],answer:1,why:'The workload exchanges the platform identity it already has for a role, so no secret is stored anywhere.',whyWrong:['Authorization still applies through the role permissions.','','Auditing improves, since the original identity is recorded.','The role remains; only the bootstrap secret disappears.']},
    {q:'After assuming a role, what should the audit log record?',options:['Only the role','Only the original caller','Both the original identity and the role assumed','Neither, it is anonymous'],answer:2,why:'Like the act claim, recording both preserves the answer to "who did this?" across the hop.',whyWrong:['Then attribution to a person is lost.','Then you cannot tell what permissions were used.','','Assumption is always attributable.']}
  ],
  az6: [
    {q:'A role check passes and the handler returns repo.findById(id). What is the flaw?',options:['The role check is wrong','No object-level check — changing the id returns another customer record','The query is slow','The id should be a string'],answer:1,why:'This is IDOR, or broken object-level authorization: endpoint authorization passed, ownership was never checked.',whyWrong:['The role check is fine and passed.','','Performance is not the issue.','The type is irrelevant.']},
    {q:'Does replacing sequential ids with UUIDs fix IDOR?',options:['Yes, they cannot be guessed','No — it is obscurity, not authorization; references leak constantly','Yes, if they are version 4','Only for public APIs'],answer:1,why:'Unguessable ids stop casual enumeration, but references appear in links, logs, exports and tickets. Do both, and never let the first substitute for the second.',whyWrong:['Guessing is only one way to obtain a reference.','','The version does not change the argument.','The argument applies everywhere.']},
    {q:'Where should the tenant constraint live?',options:['In a check after the fetch','In the query itself, so the wrong tenant simply finds nothing','In the UI','In the load balancer'],answer:1,why:'Check-after fails the moment somebody adds a new query, and somebody always does. A repository that cannot fetch across tenants cannot leak across tenants.',whyWrong:['It works until the next call site forgets.','','The UI is not an authorization boundary.','A proxy does not know who owns record 4417.']},
    {q:'Why can a gateway not enforce object-level authorization?',options:['It is too slow','It does not know who owns record 4417 — only the service holding the data does','Gateways cannot read tokens','It would break TLS'],answer:1,why:'Coarse checks at the edge, ownership checks next to the data. A design that pushes all authorization to the perimeter has no answer to IDOR.',whyWrong:['Speed is not the limitation.','','Gateways read tokens perfectly well.','TLS is unrelated.']},
    {q:'An API returns the full entity and the UI hides the salary field. What is wrong?',options:['Nothing, the user cannot see it','The JSON already contains it and anyone can open developer tools','The field should be renamed','It should be cached'],answer:1,why:'Mask or omit at serialisation, driven by the caller permissions. The UI is not an authorization boundary.',whyWrong:['They can see it in the network tab in seconds.','','Renaming hides nothing.','Caching makes it worse.']}
  ],
  az7: [
    {q:'What is the difference between a group and a role?',options:['They are the same','A group is a collection of people; a role is a collection of permissions','A role is bigger','Groups are only in LDAP'],answer:1,why:'"Who is in Finance?" is an HR question; "what may Finance do?" is a security question. Collapsing them means org-chart changes become unreviewed permission changes.',whyWrong:['They are administered differently and reviewed differently.','','Size is not the distinction.','Groups exist in every identity system.']},
    {q:'Why must a nested-group walk track visited nodes?',options:['For performance','Because nothing prevents a cycle, and a naive recursive walk would never terminate','To sort the output','To count members'],answer:1,why:'Group graphs can contain cycles, so the traversal needs a visited set. It is a graph problem, and it is where hand-rolled code fails.',whyWrong:['Performance is a side benefit, not the reason.','','Ordering is unrelated.','Counting does not require it.']},
    {q:'How does most accidental over-permissioning happen with groups?',options:['Someone grants a permission directly','Someone nests a group under a broader parent, silently granting its access to everyone above','Passwords are shared','Tokens expire late'],answer:1,why:'No permission was ever granted — the shape of the tree changed, and inheritance did the rest.',whyWrong:['Direct grants are visible and reviewable.','','Unrelated to group structure.','Unrelated.']},
    {q:'Long-tenured employees intermittently get 431 responses after login. What is the likely cause?',options:['Their password is too long','Token bloat — every group emitted as a claim overflows proxy header limits','Their account is locked','Clock skew'],answer:1,why:'Users in hundreds of groups produce oversized headers. Emit only groups relevant to the audience, send ids rather than names, or look them up at the API.',whyWrong:['Passwords are not in the token.','','A lock produces a clear error.','Skew causes expiry errors, not 431s.']},
    {q:'What number should an access review report for a person?',options:['Their direct group memberships','Their effective permissions — the flattened union across all groups, nested and direct','The number of groups','Their last login'],answer:1,why:'If you cannot produce that on demand you cannot answer the only question an auditor will ask.',whyWrong:['Direct membership hides everything inherited.','','A count says nothing about access.','Activity is a different question.']}
  ],
  az8: [
    {q:'Under deny-overrides, two policies permit and one denies. What is the result?',options:['Permit, by majority','Deny','Not applicable','It depends on order'],answer:1,why:'A prohibition should not be defeatable by adding another rule somewhere else. This is the safe default.',whyWrong:['Policy combination is not a vote.','','Some policies did apply.','Ordering matters for first-applicable, not this.']},
    {q:'Why is permit-overrides risky as a general setting?',options:['It is slower','One careless broad grant silently undoes every restriction','It cannot express deny','It is not standardised'],answer:1,why:'Occasionally justified for break-glass, but as a default it means the weakest rule wins.',whyWrong:['Performance is identical.','','It can express deny; deny just loses.','It is a standard algorithm.']},
    {q:'What must happen when no policy matches a request?',options:['Permit','Deny','Log and permit','Ask the user'],answer:1,why:'Default deny. Default permit means every resource nobody wrote a rule for is public, and you find out from the outside.',whyWrong:['That is the failure mode.','','Logging does not make it safe.','Not a decision procedure.']},
    {q:'Why keep "not applicable" distinct from "deny" inside the engine?',options:['It runs faster','It distinguishes "a rule deliberately blocked this" from "no rule covered this" — very different bugs','The spec requires three values','To reduce log volume'],answer:1,why:'Both collapse to denied at the enforcement point, but they need different fixes.',whyWrong:['No performance difference.','','Nothing requires it; it is good practice.','It adds detail rather than reducing it.']},
    {q:'What is the most valuable output of a policy engine, beyond the decision itself?',options:['The response time','Which policy decided','The number of policies evaluated','The engine version'],answer:1,why:'Without it, debugging is guesswork, and the standard response to an unexplained denial is to add a broad permit until it works.',whyWrong:['Useful for ops, not for correctness.','','A count explains nothing.','Irrelevant to the decision.']}
  ],
  am4b: [
    {q:'What makes a method phishing-resistant?',options:['A longer code','The authenticator itself checks who is asking, because the origin is part of the cryptographic operation','Sending it over TLS','Expiring in 30 seconds'],answer:1,why:'If the factor is something the user can read out and type, they can be induced to read it to an attacker. A code has no idea which site asked.',whyWrong:['Length does not help against relay.','','TLS protects the wire, not the destination.','A proxy relays within the window.']},
    {q:'An attacker sends repeated push approvals at 3am until the user taps to make it stop. What is the defence?',options:['Longer push timeouts','Number matching — the user must type digits shown on the login screen','More frequent pushes','Switching to SMS'],answer:1,why:'Number matching defeats blind approval outright, because the user must read something from the real login screen.',whyWrong:['A longer window helps the attacker.','','That worsens the fatigue.','SMS is weaker still.']},
    {q:'A user has a passkey enrolled and also SMS as a fallback. How strong is the account?',options:['As strong as the passkey','As strong as SMS','The average of the two','Stronger than either alone'],answer:1,why:'The weakest enrolled method is the account real strength, because an attacker will always claim to have lost the strong one.',whyWrong:['Only if the weak fallback is removed.','','Security does not average.','Adding a weak path never strengthens.']},
    {q:'Why should a biometric never be sent to a server?',options:['It is too large','It is a password you can never change, and it cannot be revoked','Servers cannot store images','It would be slow'],answer:1,why:'A biometric is a local gesture that unlocks a key on the device, not a factor you transmit.',whyWrong:['Size is not the concern.','','They can, which is the danger.','Speed is irrelevant.']},
    {q:'Which is the most common route to taking over an account protected by strong MFA?',options:['Breaking the cryptography','The account recovery flow','Guessing the PIN','Cloning the security key'],answer:1,why:'A hardware key protecting an account whose recovery is an emailed link is protected by email.',whyWrong:['Nobody breaks the cryptography.','','PINs are rate-limited by the authenticator.','Cloning is impractical.']}
  ],
  am4c: [
    {q:'What are the two specifications that make up FIDO2?',options:['WebAuthn and CTAP2','OAuth and OIDC','TLS and X.509','SAML and XML-DSig'],answer:0,why:'WebAuthn is the browser API your code calls; CTAP2 is how the browser talks to an external authenticator.',whyWrong:['','Different family entirely.','Transport and certificates, not FIDO2.','A different federation stack.']},
    {q:'A user signs in with Touch ID rather than a USB key. What changes on your server?',options:['Nothing — both present an identical WebAuthn surface','It must speak CTAP2','It must verify attestation','It must store a different key type'],answer:0,why:'A platform authenticator involves no CTAP at all, but the server sees the same ceremony either way, and generally should not care.',whyWrong:['','CTAP is between the browser and an external device.','Attestation is optional in both cases.','The key format is the same.']},
    {q:'What does a discoverable (resident) credential enable?',options:['Faster signatures','Usernameless login, because the authenticator knows which accounts it holds','Longer keys','Offline verification'],answer:1,why:'Non-discoverable credentials wrap the key into the credential id, so the server must say which credentials to try, meaning the user identifies themselves first.',whyWrong:['Signing speed is unchanged.','','Key length is unrelated.','Verification is offline either way.']},
    {q:'A page at login.example.com registers a credential with rpId "com". What happens?',options:['It works across all subdomains','It is rejected as a public suffix','It works but only on that host','It silently becomes example.com'],answer:1,why:'The RP ID must be the origin domain or a registrable suffix of it. A public suffix would scope the credential across an entire TLD.',whyWrong:['That is what example.com would do.','','Rejected, not narrowed.','No silent correction occurs.']},
    {q:'Why choose the RP ID carefully before registering anyone?',options:['It appears in the UI','It is baked into every credential and cannot be changed without re-registering every user','It affects signature speed','It determines the key algorithm'],answer:1,why:'Pick the broadest domain you might ever need at the start, or you will invalidate every credential later.',whyWrong:['Users never see it.','','No performance effect.','Algorithms come from pubKeyCredParams.']}
  ],
  am8b: [
    {q:'Why must the user handle not be an email address?',options:['Emails are too long','It is stored on the authenticator and may be displayed, so it would leak to anyone holding the device','Emails contain invalid characters','It must be numeric'],answer:1,why:'The user handle should be an opaque, stable id you can key on, not a personal identifier.',whyWrong:['Length is not the issue.','','Encoding is not the problem.','It need not be numeric.']},
    {q:'What is the difference between the UP and UV flags?',options:['They are the same','UP means someone touched the device; UV means a PIN or biometric was checked locally','UP is for platform authenticators only','UV means the server verified the user'],answer:1,why:'UP is one factor; UV makes the authenticator two factors on its own. Requesting userVerification is only a preference — you must check the bit.',whyWrong:['They carry different meanings.','','Both apply to either type.','Verification happens on the authenticator, not the server.']},
    {q:'What do the BE and BS flags tell you?',options:['The battery state','Whether the credential can be synced, and whether it currently is','The key algorithm','The signature counter'],answer:1,why:'Backup eligible and backup state distinguish a synced passkey from a device-bound credential, and BE cannot change after registration.',whyWrong:['Not a hardware indicator.','','Algorithms are in the COSE key.','That is signCount.']},
    {q:'Why is attestation: "none" a reasonable default?',options:['Attestation is insecure','Verifying it properly needs trust anchors and metadata, and phishing resistance comes from origin binding rather than knowing the brand','It is faster to parse','Browsers ignore attestation'],answer:1,why:'It is genuinely useful only when an enterprise must enforce approved authenticator models. Otherwise it adds a privacy cost and no security benefit.',whyWrong:['It is secure, just usually unnecessary.','','Parsing cost is trivial.','Browsers pass it through.']},
    {q:'An origin check is written as origin.startsWith("https://login.example.com"). What gets in?',options:['Nothing, it is safe','https://login.example.com.evil.com','Only subdomains','Only HTTP origins'],answer:1,why:'Origin validation must be exact set membership against an allow-list, never a prefix or contains comparison.',whyWrong:['It is a real and common vulnerability.','','It admits far more than subdomains.','Scheme is not the issue.']}
  ],
  am8c: [
    {q:'What does an empty allowCredentials list trigger?',options:['An error','Usernameless login — the authenticator offers whatever discoverable credentials it holds','A fallback to password','Registration instead of login'],answer:1,why:'The authenticator returns a userHandle identifying who was chosen, which is why the handle must be a stable opaque id.',whyWrong:['It is a valid and deliberate request.','','No fallback is implied.','The ceremony type is set by the API call.']},
    {q:'What exactly does the authenticator sign during authentication?',options:['Only the challenge','authenticatorData concatenated with SHA-256 of clientDataJSON','The user password','The credential id'],answer:1,why:'Because the browser writes the origin into clientDataJSON and its hash is inside the signed bytes, a phishing proxy cannot alter it.',whyWrong:['The challenge alone would not bind the origin.','','No password is involved.','The credential id is not the signed payload.']},
    {q:'A synced passkey reports signCount 0 and your stored value is 0. What should you do?',options:['Reject it as a cloned authenticator','Accept it — counters are unsupported, which is normal for synced passkeys','Increment the stored value','Force re-registration'],answer:1,why:'Treating 0 as a regression locks out every synced-passkey user. A genuine regression is a signal to log and investigate, not an automatic rejection.',whyWrong:['That is the lockout bug.','','There is nothing to increment.','Nothing is wrong.']},
    {q:'You look up the stored public key by credential id and verify the signature. What else must you check?',options:['Nothing more','That the credential belongs to the account being logged into','The key length','The authenticator brand'],answer:1,why:'Otherwise a credential valid for Bob authenticates Ada — an account-confusion bug.',whyWrong:['One step is missing.','','Length is fixed by the algorithm.','The brand is irrelevant.']},
    {q:'WebAuthn is very hard to attack directly. Where do realistic attacks go instead?',options:['The signature algorithm','Recovery, enrollment, downgrade and post-login session theft','The random challenge','The USB protocol'],answer:1,why:'The cryptography holds, so everything depends on the flows around it — and a login that was unphishable still produces an ordinary bearer cookie.',whyWrong:['ES256 is not the weak point.','','A correctly generated challenge is not attackable.','CTAP is not the soft spot.']}
  ],
  ao4b: [
    {q:'Which check actually makes a token sender-constrained under DPoP?',options:['Verifying the proof signature with the JWK in its own header','Comparing the thumbprint of that JWK to cnf.jkt in the access token','Checking the htu value','Checking that iat is recent'],answer:1,why:'Without it the proof shows only that someone owns some key. Comparing to cnf.jkt is what ties the key to this token.',whyWrong:['Necessary but circular on its own — it proves the sender holds that key, not that the token was issued to it.','','That stops endpoint replay, not token theft.','That limits the replay window only.']},
    {q:'What are htm and htu for in a DPoP proof?',options:['Identifying the client','Binding the proof to this HTTP method and URI, so a captured proof cannot be reused elsewhere','Encrypting the request','Naming the audience'],answer:1,why:'A proof captured against one endpoint is useless against another.',whyWrong:['The jwk identifies the key, not the client.','','DPoP signs, it does not encrypt.','That is the token aud claim.']},
    {q:'Why do server-provided DPoP nonces exist when a replay cache already works?',options:['They are faster to compute','A replay cache needs shared state across a fleet; a nonce lets the server choose the value with no per-request storage','They make proofs longer','They replace the signature'],answer:1,why:'Shared jti state is exactly what stateless tokens were meant to avoid, and a nonce cannot be minted in advance.',whyWrong:['Computation is not the issue.','','Length is irrelevant.','The signature is still required.']},
    {q:'Why must the refresh token be constrained too?',options:['It is larger','Otherwise a stolen refresh token simply mints new access tokens, making the constraint pointless','Refresh tokens expire faster','The spec forbids bearer refresh tokens everywhere'],answer:1,why:'Constraining access tokens while leaving refresh bearer protects nothing.',whyWrong:['Size is irrelevant.','','They live far longer.','It is required for DPoP public clients specifically.']},
    {q:'When is mTLS-bound preferable to DPoP?',options:['In a browser app','In service-to-service and regulated environments where a PKI already exists','Whenever CDNs are involved','For mobile apps'],answer:1,why:'mTLS is hardware-backed and harder to steal, but needs a PKI and TLS terminated where the certificate is still visible.',whyWrong:['Client certificates effectively do not work in browsers.','','Client certificates often break through proxies and CDNs.','DPoP suits mobile far better.']}
  ],
  oa8b: [
    {q:'Why is storing an access token in localStorage discouraged?',options:['It is too small','Any JavaScript on the page can read it, so one XSS or one bad dependency exfiltrates it','It is not encrypted at rest','Browsers are deprecating it'],answer:1,why:'If your app can read the token, so can injected script. No care with the flow changes that.',whyWrong:['Capacity is not the issue.','Encryption would not help, since the app must decrypt it to use it.','','localStorage is not being removed.']},
    {q:'What does a BFF actually eliminate?',options:['XSS','The durable credential in the browser, so an XSS cannot grant lasting access','CSRF','The need for a session'],answer:1,why:'Injected script can still act as the user while the page is open, but there is no token to steal and reuse from elsewhere.',whyWrong:['XSS remains possible.','','A BFF reintroduces CSRF, because the browser now authenticates with a cookie.','It creates one.']},
    {q:'Adopting a BFF reintroduces which problem?',options:['Token theft','CSRF, because the browser authenticates with a cookie','Weak passwords','Clock skew'],answer:1,why:'SameSite cookies plus a per-session CSRF token on state-changing requests is the standard answer.',whyWrong:['That is what the BFF removes.','','Unrelated.','Unrelated.']},
    {q:'A team genuinely cannot run any backend. What is the least-bad option?',options:['Refresh token in localStorage','A short-lived access token in memory with PKCE and no refresh token in the browser','A long-lived access token in a cookie readable by script','An API key in the bundle'],answer:1,why:'Exposed while the page is open, but nothing durable is left behind, and re-authentication on refresh is accepted.',whyWrong:['The worst case: one XSS yields lasting access.','','A script-readable cookie is no better than localStorage.','A key in a bundle is public.']},
    {q:'Conceptually, what does a BFF turn a SPA back into?',options:['A public client','A confidential client with a session, which is what server-rendered apps always were','A resource server','An identity provider'],answer:1,why:'The industry spent a decade moving tokens into the browser and has spent recent years moving them back out.',whyWrong:['It stops being a public client — it now has a real secret.','','The BFF calls the API; it is not the API.','It does not authenticate users itself.']}
  ],
  oa11: [
    {q:'What is OAuth 2.1, fundamentally?',options:['A new protocol incompatible with OAuth 2.0','A consolidation that folds the Security BCP into the base spec and removes discouraged grants','A replacement for OpenID Connect','A new token format'],answer:1,why:'It invents nothing. If you have been following the Security BCP you are already writing OAuth 2.1.',whyWrong:['There is no protocol incompatibility.','','OIDC still sits on top, unchanged.','Token formats are untouched.']},
    {q:'Which grants does OAuth 2.1 remove?',options:['Implicit and password (ROPC)','Client credentials and device code','Authorization code and refresh','Only implicit'],answer:0,why:'Implicit returned a token in the URL fragment; ROPC has the app collect the password. Both are superseded.',whyWrong:['','Both remain.','Both remain and are central.','ROPC is removed too.']},
    {q:'What is the biggest practical change for a confidential client?',options:['Nothing changes','PKCE becomes required, because it defends against code injection which a client secret does not address','It must adopt DPoP','It must stop using refresh tokens'],answer:1,why:'The old "PKCE is for public clients" guidance is obsolete.',whyWrong:['PKCE becomes mandatory.','','Sender constraint is one option for refresh tokens, not a blanket requirement.','Refresh tokens remain, with rotation or binding.']},
    {q:'How must redirect URIs be matched?',options:['By prefix','By exact string comparison, with no wildcards','By domain only','By regular expression'],answer:1,why:'Loose redirect matching is one of the most reliable ways to steal an authorization code.',whyWrong:['Prefix matching is precisely the vulnerability.','','Domain-only matching admits any path.','A regex is worse still.']},
    {q:'When auditing an existing deployment, where does the real risk usually sit?',options:['The token format','A legacy grant still enabled on the authorization server for one unmigrated client','The scope names','The key length'],answer:1,why:'The grants are removed from the specification, but servers keep supporting them for compatibility, and an enabled-but-unused grant is still enabled.',whyWrong:['Formats are unchanged by 2.1.','','Scope naming is not a 2.1 concern.','Key length is unrelated.']}
  ],
  oa2b: [
    {q:'What was the original attack PKCE was designed to stop?',options:['Password guessing','Authorization code interception, where another app registers the same custom URL scheme','Token expiry','Replay of the ID token'],answer:1,why:'A native app has no secret, so the authorization server could not tell the real app from a malicious one receiving the same redirect.',whyWrong:['Unrelated to the code flow.','','Expiry is not an attack.','That is what nonce addresses.']},
    {q:'Why does PKCE now apply to confidential clients as well?',options:['For consistency','Because of code injection, where an attacker feeds the victim a code for the attacker account — a client secret does not help','Because secrets leak','To speed up the flow'],answer:1,why:'The client is genuine; the code is foreign. The victim client holds a verifier that does not match the challenge the attacker code was bound to.',whyWrong:['It is a real attack, not tidiness.','','That is a different problem.','It adds a hash.']},
    {q:'Why is it safe for the code_challenge to travel through the browser?',options:['It is encrypted','It is a SHA-256 hash, and the verifier cannot be recovered from it','It is short-lived','The browser hides it'],answer:1,why:'The challenge is public by design; the verifier travels only on the direct back-channel POST, once, at the end.',whyWrong:['It is hashed, not encrypted.','','Lifetime is not what protects it.','URLs are highly visible.']},
    {q:'What is the PKCE downgrade attack?',options:['Forcing plain instead of S256','Omitting code_verifier at the token endpoint and hoping the server treats it as optional','Using a shorter code','Reusing an old challenge'],answer:1,why:'If a challenge was stored, the verifier must be required. Absence is failure, not a skipped optional check.',whyWrong:['A related weakness, but the downgrade is the omission.','','Code length is set by the server.','Reuse is a different flaw.']},
    {q:'How do state and code_challenge differ?',options:['They are the same protection','state binds the response to the user session (CSRF); code_challenge binds the code to the client secret','state is for mobile only','code_challenge replaces state'],answer:1,why:'You need both, and in OIDC nonce is a third thing again, binding the ID token to this login.',whyWrong:['They defend different things.','','state applies everywhere.','Neither substitutes for the other.']}
  ]
};
