/* Hand-authored, plain-English quizzes for the concept-heavy identity lessons.
   Attached in boot BEFORE the auto-generated QUIZZES map, so these win (readable
   questions instead of "factorType(\"totp\") returns…?"). Keyed by lesson id. */
window.QUIZZES_HAND = {
  idf0: [
    {q:'What does IdP stand for?',options:['Identity Provider','Internal Data Protocol','Identity Policy','Integrated Directory'],answer:0,why:'The IdP is the authority that authenticates users and issues tokens or assertions.',whyWrong:['','That is not what IdP means.','A policy is a rule set, not the authenticating authority.','A directory stores users; the IdP authenticates them.']},
    {q:'What does OIDC stand for?',options:['OpenID Connect','Open Identity Credential','Online ID Check','OAuth Identity Config'],answer:0,why:'OpenID Connect is the authentication layer built on top of OAuth 2.0.',whyWrong:['','Not a real term.','Not a real term.','Not a real term.']},
    {q:'What does MFA mean?',options:['Multi-Factor Authentication','Managed Federation Access','Multi-Field Authorization','Master File Access'],answer:0,why:'MFA requires two or more independent factors to sign in.',whyWrong:['','Made up.','Made up.','Made up.']},
    {q:'What does SSO mean?',options:['Single Sign-On','Secure Socket Option','Session Storage Object','Signed Security Officer'],answer:0,why:'Single Sign-On lets one login reach many applications.',whyWrong:['','Not a real term.','Not a real term.','Not a real term.']}
  ],
  idffed: [
    {q:'In federation, which party authenticates the user and issues the signed proof?',options:['Identity Provider (IdP)','Relying Party (RP)','The browser','The API gateway'],answer:0,why:'The IdP vouches for the user; everyone else relies on that.',whyWrong:['','The RP relies on the proof, it does not create it.','The browser only carries the proof.','A gateway routes traffic; it does not authenticate the user.']},
    {q:'What does the Service Provider / Relying Party do?',options:['Relies on the IdP proof instead of checking a password','Stores every user password','Signs the token','Runs the MFA prompt'],answer:0,why:'The whole point of federation is that the app trusts the IdP rather than holding passwords.',whyWrong:['','That is what federation avoids.','The IdP signs the token, not the RP.','The IdP handles authentication and MFA.']},
    {q:'Why can a random website not fake "Google says this is you"?',options:['The RP only accepts tokens signed by the pre-trusted IdP key','Google emails a confirmation','Browsers block it','It cannot be prevented'],answer:0,why:'Trust is set up in advance with the IdP public keys, so only real signatures verify.',whyWrong:['','No email is involved in token verification.','The browser does not verify the signature; the RP does.','It absolutely can be prevented by signature verification.']}
  ],
  idffed2: [
    {q:'Which piece is the authority that authenticates users?',options:['Identity Provider (IdP)','Relying Party','Access token','JWKS endpoint'],answer:0,why:'The IdP is the authenticating authority.',whyWrong:['','The relying party consumes the proof.','A token is the proof, not the authority.','JWKS just publishes the keys.']},
    {q:'What is the "proof" passed in federation?',options:['A signed token or assertion','A username and password','A session cookie only','A TLS certificate'],answer:0,why:'The IdP issues a signed token (OIDC) or assertion (SAML) the app can verify.',whyWrong:['','Passwords are what federation avoids sending around.','A cookie tracks a local session, it is not the federated proof.','A certificate proves a server, not the user login.']},
    {q:'Where does the IdP publish the keys used to verify its tokens?',options:['A JWKS endpoint / SAML metadata','Inside the access token','In the user cookie','In the client secret'],answer:0,why:'The IdP publishes public keys at JWKS (OIDC) or in metadata (SAML) so relying parties can verify signatures.',whyWrong:['','The token carries a signature, not the verification key.','Cookies do not carry IdP keys.','The client secret authenticates the app, it is not the IdP signing key.']}
  ],
  am2: [
    {q:'A password is which kind of authentication factor?',options:['Something you know (knowledge)','Something you have (possession)','Something you are (inherence)','Somewhere you are'],answer:0,why:'A password is knowledge — a secret you remember.',whyWrong:['','Possession is a device or key you hold.','Inherence is a biometric.','Location is a context signal, not this factor.']},
    {q:'A one-time code from an authenticator app is which factor?',options:['Something you have (possession)','Something you know','Something you are','A recovery factor'],answer:0,why:'The code comes from a device you possess.',whyWrong:['','Knowledge is a memorized secret.','Inherence is a biometric.','Recovery is a flow, not a factor category.']},
    {q:'A fingerprint is which factor?',options:['Something you are (inherence)','Something you know','Something you have','A knowledge factor'],answer:0,why:'A biometric is inherence — something you are.',whyWrong:['','Knowledge is memorized.','Possession is a held device.','A knowledge factor is a memorised secret, not a biometric.']},
    {q:'True MFA combines factors from…',options:['two or more different categories','two passwords','the same category twice','one strong factor'],answer:0,why:'The categories must differ, so stealing one (a password) is not enough.',whyWrong:['','Two passwords are both knowledge — still one factor type.','Same category twice is not multi-factor.','One factor, however strong, is single-factor.']}
  ],
  am6: [
    {q:'Which NIST scale measures how strongly the real-world identity was proofed at enrollment?',options:['IAL (Identity Assurance Level)','AAL (Authenticator Assurance Level)','FAL (Federation Assurance Level)','TLS level'],answer:0,why:'IAL is about identity proofing.',whyWrong:['','AAL is about login strength, not proofing.','FAL is about how the assertion is protected.','TLS is transport security, not an identity scale.']},
    {q:'Which scale measures how strong the login authentication is?',options:['AAL','IAL','FAL','MFA-2'],answer:0,why:'AAL rates authenticator strength (single factor, MFA, hardware).',whyWrong:['','IAL rates identity proofing.','FAL rates the federated assertion.','Not a real scale.']},
    {q:'MFA corresponds to which authenticator level?',options:['AAL2','AAL1','AAL3','IAL2'],answer:0,why:'AAL2 requires two factors (MFA).',whyWrong:['','AAL1 is a single factor.','AAL3 additionally requires a hardware, phishing-resistant authenticator.','IAL2 is a proofing level, not an authenticator level.']},
    {q:'A hardware, phishing-resistant authenticator (security key) is…',options:['AAL3','AAL1','FAL1','IAL1'],answer:0,why:'AAL3 is the highest authenticator level and requires hardware-backed, phishing-resistant auth.',whyWrong:['','AAL1 is single factor.','FAL is about assertions, not authenticators.','IAL1 is self-asserted identity, unrelated.']}
  ],
  am8: [
    {q:'Creating a new passkey key pair for a site is which WebAuthn ceremony?',options:['Registration (attestation)','Authentication (assertion)','Recovery','Rotation'],answer:0,why:'Registration creates the key pair and may attest the authenticator.',whyWrong:['','Authentication signs a challenge with an existing key.','Recovery is a separate account flow.','Rotation is not a WebAuthn ceremony.']},
    {q:'Signing a server challenge to log in is which ceremony?',options:['Authentication (assertion)','Registration (attestation)','Enrollment','Provisioning'],answer:0,why:'Authentication has the authenticator sign a fresh challenge (an assertion).',whyWrong:['','Registration is the one-time key-pair creation.','Enrollment is another word for registration, not login.','Provisioning creates accounts, not this signature.']},
    {q:'In WebAuthn, the private key…',options:['never leaves the device','is stored on the server','is emailed to the user','is the client secret'],answer:0,why:'The private key stays in the device, which is what makes passkeys phishing-resistant.',whyWrong:['','The server only stores the public key.','Keys are never emailed.','That is an OAuth concept, not a passkey.']}
  ],
  az2: [
    {q:'In RBAC, permissions are granted to a user through…',options:['roles','their IP address','the session id','the request path'],answer:0,why:'Users get roles; roles carry permissions.',whyWrong:['','IP is a network detail, not an RBAC grant.','A session id identifies a login, not permissions.','The path is what is protected, not how access is granted.']},
    {q:'A "viewer" role typically has which permission?',options:['read','read, write, delete','write','admin'],answer:0,why:'A viewer can read only — least privilege.',whyWrong:['','That is an admin-level set.','Viewers do not write.','Admin is the most powerful role, not a viewer.']},
    {q:'Which principle says a role should hold only the access it truly needs?',options:['Least privilege','Separation of duties','Defense in depth','Fail-closed'],answer:0,why:'Least privilege grants the minimum access required.',whyWrong:['','Separation of duties splits conflicting powers between people.','Defense in depth is layered controls.','Fail-closed is a default-deny behavior, not this principle.']}
  ],
  oaclient: [
    {q:'A single-page app (SPA) is which kind of OAuth client?',options:['Public — uses PKCE, no secret','Confidential — uses a client secret','A resource server','An identity provider'],answer:0,why:'A SPA cannot hide a secret, so it is a public client and uses PKCE.',whyWrong:['','It cannot keep a secret, so it is not confidential.','The resource server is the API, not the app.','The IdP is the authority, not the app.']},
    {q:'How does a server-side (confidential) client authenticate to the token endpoint?',options:['With a client secret or a key','With the user password','It cannot authenticate','With a session cookie'],answer:0,why:'Confidential clients prove themselves with a secret or an asymmetric key.',whyWrong:['','The user password is never used by the client this way.','Confidential clients absolutely authenticate.','Cookies are for browser sessions, not client auth.']},
    {q:'Which client authentication method uses no shared secret?',options:['private_key_jwt (asymmetric key)','client_secret_basic','client_secret_post','HTTP Basic with the password'],answer:0,why:'private_key_jwt signs with a private key; the server verifies with the public key — nothing shared to leak.',whyWrong:['','Uses a shared secret.','Uses a shared secret.','Uses a password, the weakest option.']},
    {q:'Where should a client_secret be stored?',options:['A secret manager or server environment, never in front-end code','In the SPA bundle','In the redirect URL','In localStorage'],answer:0,why:'Anything shipped to the browser is public, so secrets stay server-side.',whyWrong:['','The bundle is downloadable by anyone.','URLs get logged and shared.','localStorage is readable by any script (XSS).']}
  ],
  oa10: [
    {q:'Best flow for a web or mobile app acting for a user?',options:['Authorization Code + PKCE','Client Credentials','Implicit','ROPC (password)'],answer:0,why:'Authorization Code with PKCE is the modern default for user-facing apps.',whyWrong:['','Client Credentials is for machines with no user.','Implicit is deprecated.','ROPC (password grant) is deprecated.']},
    {q:'Best flow for machine-to-machine (no user present)?',options:['Client Credentials','Authorization Code','Device flow','Implicit'],answer:0,why:'Client Credentials authenticates the service itself, with no user.',whyWrong:['','Authorization Code needs a user at a browser.','Device flow is for input-limited devices with a user.','Implicit is deprecated and user-facing.']},
    {q:'Which grant is deprecated and should be avoided?',options:['Implicit / ROPC','Authorization Code + PKCE','Client Credentials','Refresh'],answer:0,why:'Implicit and ROPC are discouraged by the OAuth Security BCP.',whyWrong:['','This is the recommended flow.','Still valid for M2M.','Refresh tokens are still used (with rotation).']}
  ],
  s2s6: [
    {q:'Inside a Kubernetes cluster or service mesh, how do services usually prove identity to each other?',options:['mTLS with workload certificates (e.g. SPIFFE/SPIRE)','A shared password in env vars','IP allowlists only','No auth inside the cluster'],answer:0,why:'Each workload gets a short-lived certificate and services verify each other with mutual TLS.',whyWrong:['','Shared static secrets are exactly what this avoids.','IP can be spoofed and is not identity.','Zero trust means never assuming the network is safe.']},
    {q:'Machine-to-machine access to an external API is typically obtained via…',options:['OAuth client-credentials tokens','the user session cookie','a hardcoded API key in the repo','SAML browser SSO'],answer:0,why:'A service gets its own token from a minting authority with the client-credentials grant.',whyWrong:['','There is no user session in M2M.','Hardcoded keys leak and cannot rotate cleanly.','SAML browser SSO needs a human at a browser.']},
    {q:'Zero trust means…',options:['verify identity and authorize every request, regardless of network location','trust anything inside the firewall','trust by IP address','authenticate once at the perimeter only'],answer:0,why:'Never trust by location; authenticate and authorize each call.',whyWrong:['','That is the old perimeter model zero trust replaces.','IP is not identity.','Perimeter-only auth is what zero trust rejects.']}
  ],
  ei2: [
    {q:'In Kerberos, what does the Authentication Service (AS) issue?',options:['A Ticket-Granting Ticket (TGT)','A service ticket','A password','A refresh token'],answer:0,why:'The AS verifies you once and issues a TGT.',whyWrong:['','The TGS issues service tickets, using your TGT.','Passwords are never handed out.','Refresh tokens are an OAuth concept.']},
    {q:'To reach a specific service you present the TGT to the TGS and receive…',options:['a service ticket','another TGT','your password back','a SAML assertion'],answer:0,why:'The TGS grants a per-service ticket so your password never reaches the service.',whyWrong:['','You already have the TGT; the TGS gives a service ticket.','Passwords are not returned.','SAML is a different protocol.']}
  ],
  ei3: [
    {q:'A new hire (Joiner) should trigger which provisioning action?',options:['Create the account','Update access','Deactivate the account','Nothing'],answer:0,why:'Joiner creates the account and grants baseline access.',whyWrong:['','Update is the Mover case.','Deactivate is the Leaver case.','Onboarding must create access.']},
    {q:'An employee who leaves (Leaver) should trigger…',options:['Deactivate/delete the account','Create a new account','Only a password reset','Nothing automatic'],answer:0,why:'Leaver deprovisions access — the biggest security win of automation.',whyWrong:['','That is the Joiner case.','A reset does not remove access.','Leaving accounts active is a top breach cause.']},
    {q:'Which standard automates pushing these create/update/deactivate operations?',options:['SCIM','SAML','OAuth','LDAP browsing'],answer:0,why:'SCIM is the provisioning API that syncs accounts across systems.',whyWrong:['','SAML carries login assertions, not provisioning.','OAuth is authorization for API access.','LDAP is a directory query protocol, not the provisioning push.']}
  ],
  ei4b: [
    {q:'Workforce with an HR system of record is best served by…',options:['SCIM pre-provisioning','JIT only','Manual creation','No provisioning'],answer:0,why:'SCIM keeps accounts in sync from the HR source and supports clean deprovisioning.',whyWrong:['','JIT alone will not deprovision leavers.','Manual does not scale for a workforce.','Some provisioning is required.']},
    {q:'A huge, unpredictable external / customer population is best served by…',options:['JIT provisioning','Pre-importing every user','Manual creation','LDAP sync'],answer:0,why:'JIT creates the account on first login, so you never pre-import millions of users.',whyWrong:['','Pre-importing millions is impractical.','Manual cannot scale to consumers.','LDAP sync fits a directory-backed workforce, not open consumers.']},
    {q:'The classic gap with JIT provisioning is that it…',options:['creates accounts but does not deprovision them','cannot create accounts','requires SAML','is slower than manual'],answer:0,why:'JIT provisions on first login but never removes access, so pair it with SCIM or reviews.',whyWrong:['','Creating accounts is exactly what JIT does.','JIT works with OIDC or SAML.','JIT is far faster than manual.']}
  ],
  biz: [
    {q:'Netflix serving individual consumers is an example of…',options:['B2C','B2B','B2B2C','P2P'],answer:0,why:'Selling directly to individual consumers is B2C.',whyWrong:['','B2B serves other businesses.','B2B2C serves a business that serves its own consumers.','P2P is not a business model here.']},
    {q:'Salesforce serving other companies (each a tenant) is…',options:['B2B','B2C','B2B2C','C2C'],answer:0,why:'Selling to businesses, whose employees are the users, is B2B.',whyWrong:['','B2C is direct-to-consumer.','B2B2C adds the tenant serving its own consumers.','C2C is consumer-to-consumer.']},
    {q:'Shopify (merchants who serve their own shoppers through the platform) is…',options:['B2B2C','B2C','B2B','B2G'],answer:0,why:'You serve a business and, through it, that business own consumers — two identity layers.',whyWrong:['','B2C is direct to consumers only.','B2B stops at the business tenant.','B2G is business-to-government.']},
    {q:'Which models are inherently multi-tenant?',options:['B2B and B2B2C','B2C only','B2C and B2B','none'],answer:0,why:'Serving businesses means each customer is an isolated tenant.',whyWrong:['','B2C is single-population, not tenant-based.','B2C is not multi-tenant.','Multi-tenancy is central to B2B and B2B2C.']}
  ],
  ao3: [
    {q:'PAR (Pushed Authorization Requests) improves security by…',options:['sending the request parameters to the server first, off the browser URL','encrypting the database','rotating refresh tokens','hashing passwords'],answer:0,why:'PAR moves sensitive parameters off the front channel into a back-channel push.',whyWrong:['','Unrelated to database encryption.','That is refresh-token rotation.','That is password storage.']},
    {q:'RAR (Rich Authorization Requests) provides…',options:['fine-grained, structured authorization details beyond coarse scopes','a faster token endpoint','a new password hash','mutual TLS'],answer:0,why:'RAR replaces blunt scopes with structured detail like "transfer up to 500 from account X".',whyWrong:['','It is about detail, not speed.','Nothing to do with passwords.','mTLS is a client-auth mechanism, not RAR.']},
    {q:'DPoP is about…',options:['sender-constrained (proof-of-possession) tokens','compressing tokens','user consent screens','password storage'],answer:0,why:'DPoP binds a token to a key the client must prove, so a stolen token is useless.',whyWrong:['','Not compression.','Not consent.','Not password storage.']}
  ],
  ao5: [
    {q:'Which defense stops CSRF on the OAuth redirect?',options:['The state parameter','A nonce','PKCE','Exact redirect_uri matching'],answer:0,why:'The state parameter is a random value the client checks on return, blocking CSRF.',whyWrong:['','nonce defends ID-token replay, not the redirect CSRF.','PKCE defends code interception.','Exact redirect_uri defends open redirect / mix-up.']},
    {q:'Which defends against authorization-code interception by public clients?',options:['PKCE','state','nonce','CORS'],answer:0,why:'PKCE ties the code to a secret only the real client holds, so a stolen code is useless.',whyWrong:['','state defends CSRF.','nonce defends replay of ID tokens.','CORS is a browser policy, not this defense.']},
    {q:'Which defends against replay of a token or ID token?',options:['A one-time nonce','state','exact redirect_uri','a longer secret'],answer:0,why:'A nonce (plus short expiry) makes a captured token single-use.',whyWrong:['','state defends CSRF on the redirect.','redirect_uri matching defends open redirect.','Length alone does not stop replay.']},
    {q:'Open redirect / mix-up is mitigated by…',options:['registering and matching exact redirect_uri values','wildcards in redirect_uri','longer tokens','disabling PKCE'],answer:0,why:'Only exact, pre-registered redirect URIs should be accepted.',whyWrong:['','Wildcards are the vulnerability, not the fix.','Token length is unrelated.','Disabling PKCE weakens security.']}
  ],
  ig5: [
    {q:'CIAM (Customer IAM) primarily serves…',options:['customers / consumers','employees','service accounts','admins only'],answer:0,why:'CIAM is about external consumers, optimizing self-service and scale.',whyWrong:['','Employees are workforce IAM.','Service accounts are machine identity.','Admins are a small subset, not the focus.']},
    {q:'Workforce IAM primarily serves…',options:['employees and contractors','external customers','the public','IoT devices'],answer:0,why:'Workforce IAM governs staff, emphasizing control and deprovisioning.',whyWrong:['','Customers are CIAM.','The public is CIAM territory.','Devices are workload/machine identity.']}
  ],
  idcap: [
    {q:'In the auth lifecycle, the "register" step should…',options:['hash the password (never store plaintext)','issue tokens','revoke the session','validate a token'],answer:0,why:'Registration stores a slow, salted hash of the password.',whyWrong:['','Issuing tokens happens at login.','Revoking is logout.','Validation happens on each request.']},
    {q:'On "login", the server…',options:['issues tokens (access + refresh)','hashes the password','deletes the account','rotates signing keys'],answer:0,why:'After verifying credentials, login mints the tokens.',whyWrong:['','Hashing is a registration step.','Login does not delete anything.','Key rotation is an operational task, not login.']},
    {q:'On each "request", the server…',options:['validates the access token, then authorizes the action','re-hashes the password','issues a new refresh token','creates the account'],answer:0,why:'Every request checks the token (iss/aud/exp) and then the permission.',whyWrong:['','No password is involved per request.','Refresh happens on the refresh endpoint, not every request.','The account already exists.']},
    {q:'On "logout", the server…',options:['revokes the session','issues a token','hashes a password','creates a session'],answer:0,why:'Logout must end the session server-side, not just drop the cookie.',whyWrong:['','Tokens are issued at login.','Hashing is registration.','Creating a session is login.']}
  ],
  am9: [
    {q:'Where do most account breaches actually come from?',options:['Credential stuffing (replaying passwords leaked elsewhere)','Zero-day exploits','Tricking admins in person','Brute-forcing strong passwords'],answer:0,why:'Attackers replay username/password pairs leaked from other sites, betting on reuse — cheap and automated.',whyWrong:['','Zero-days are rare and expensive next to stuffing.','That happens but is not the bulk of takeovers.','Brute-forcing strong passwords is slow and usually rate-limited.']},
    {q:'Which single control makes a leaked password insufficient on its own?',options:['MFA','A longer password policy','Security questions','Login email notifications'],answer:0,why:'With MFA, a correct-but-leaked password still cannot complete the login.',whyWrong:['','Length does not help once the exact password has leaked.','Knowledge answers are also leakable and guessable.','Notifications warn after the fact; they do not block.']},
    {q:'Checking a new password against known-breached lists is done safely with…',options:['k-anonymity (only a hash prefix leaves you)','sending the full password to a third party','downloading every breach in full','an email round-trip'],answer:0,why:'Services like Have I Been Pwned use k-anonymity, so the password itself never leaves your server.',whyWrong:['','You must never send the full password.','Impractical and unnecessary.','Unrelated to breach checks.']},
    {q:'A flood of failed logins across many accounts is best stopped by…',options:['rate limiting + bot detection','a CAPTCHA on every page','taking the site offline','longer sessions'],answer:0,why:'Throttle the automation and detect bots; keep humans unblocked.',whyWrong:['','CAPTCHA everywhere punishes real users — a last resort.','That is denial of service to yourself.','Unrelated to the attack.']}
  ],
  iddid: [
    {q:'In decentralized identity, where do your credentials live?',options:['In your own wallet','On a central IdP server','In a shared database','Only in the browser cache'],answer:0,why:'The holder keeps Verifiable Credentials in a wallet and presents them directly.',whyWrong:['','There is no central IdP mediating each sign-in.','They are not held in a shared database.','A wallet is durable storage, not just cache.']},
    {q:'A Verifiable Credential is…',options:['a signed, tamper-evident claim issued by an authority','a username and password','a session cookie','an IP allowlist'],answer:0,why:'A VC is a cryptographically signed claim (e.g. "over 18") you can present and others can verify.',whyWrong:['','It is not a password-style credential.','A cookie is a local session token.','Unrelated to VCs.']},
    {q:'Selective disclosure lets you…',options:['prove you are over 18 without revealing your birthdate','share your whole profile at once','skip verification entirely','reset your password'],answer:0,why:'Selective disclosure / zero-knowledge proofs reveal only the fact needed, nothing more.',whyWrong:['','That is the opposite of the goal.','Verification still happens on the disclosed fact.','Unrelated.']},
    {q:'Compared with federation, decentralized identity…',options:['has no central IdP that sees every login','still requires a central IdP','cannot be verified without the issuer online','is exactly the same thing'],answer:0,why:'No central authority mediates each sign-in, which improves privacy and resilience.',whyWrong:['','It removes the central IdP.','A verifier checks the signature without contacting the issuer.','It is a distinct model from federation.']}
  ],
  igaudit: [
    {q:'To prove who did what and when, you need…',options:['an immutable audit log','more RAM','a faster CPU','a bigger cache'],answer:0,why:'An append-only, tamper-evident audit trail is the evidence auditors and investigators need.',whyWrong:['','Hardware does not make actions provable.','Speed is unrelated to auditability.','Caching is unrelated.']},
    {q:'Real-time detection of suspicious login patterns is the job of…',options:['a SIEM','the password hasher','the stylesheet','the DNS resolver'],answer:0,why:'A SIEM ingests the logs and alerts on patterns like failed-login bursts or a new admin.',whyWrong:['','Hashing protects stored passwords, not detection.','Unrelated.','Unrelated.']},
    {q:'Which must NEVER appear in identity logs?',options:['full tokens or secrets','the user id','the timestamp','the action name'],answer:0,why:'Logging secrets or full tokens turns your logs into a breach; log identifiers and metadata only.',whyWrong:['','The subject id is expected and useful.','Timestamps are required.','The action is the whole point of the log.']},
    {q:'Frameworks like SOC 2 and NIST 800-63 map their controls to identity practices such as…',options:['MFA, least privilege, deprovisioning, audit logs','screen colors','marketing copy','the database vendor'],answer:0,why:'Those frameworks require exactly these identity controls, evidenced by your audit trail.',whyWrong:['','Not a security control.','Not a control.','Not a control.']}
  ]
};
